### ISSUE TITLE
Validator Stopped After Running for Several Hours ```AxiosError: read ECONNRESET```

### ISSUE THREAD

**Issue by bednarczyk9** [Shardeum/shardeum-bug-reporting#102]
Node works few hours (with standby status) and stop working. I set script which check status of node every 10 seconds. I receive the following error message in console:

```shell
AxiosError: read ECONNRESET
    at Function.AxiosError.from (/home/node/app/cli/node_modules/axios/dist/node/axios.cjs:789:14)
    at RedirectableRequest.handleRequestError (/home/node/app/cli/node_modules/axios/dist/node/axios.cjs:2744:25)
    at RedirectableRequest.emit (node:events:390:28)
    at ClientRequest.eventHandlers.<computed> (/home/node/app/cli/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:390:28)
    at Socket.socketErrorListener (node:_http_client:447:9)
    at Socket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  syscall: 'read',
  code: 'ECONNRESET',
  errno: -104,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: null },
    validateStatus: [Function: validateStatus],
    headers: AxiosHeaders {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/1.2.2',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'get',
    url: 'http://35.200.198.232:9001/stake',
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'http:',
      path: '/stake',
      method: 'GET',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: '35.200.198.232',
      port: '9001',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/stake'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'GET /stake HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/1.2.2\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: 35.200.198.232:9001\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/stake',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '35.200.198.232',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'http://35.200.198.232:9001/stake',
    [Symbol(kCapture)]: false
  },
  cause: Error: read ECONNRESET
      at TCP.onStreamRead (node:internal/stream_base_commons:220:20) {
    errno: -104,
    code: 'ECONNRESET',
    syscall: 'read'
  }
}
AxiosError: connect ECONNREFUSED 35.200.198.232:9001
    at Function.AxiosError.from (/home/node/app/cli/node_modules/axios/dist/node/axios.cjs:789:14)
    at RedirectableRequest.handleRequestError (/home/node/app/cli/node_modules/axios/dist/node/axios.cjs:2744:25)
    at RedirectableRequest.emit (node:events:390:28)
    at ClientRequest.eventHandlers.<computed> (/home/node/app/cli/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:390:28)
    at Socket.socketErrorListener (node:_http_client:447:9)
    at Socket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  port: 9001,
  address: '35.200.198.232',
  syscall: 'connect',
  code: 'ECONNREFUSED',
  errno: -111,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: null },
    validateStatus: [Function: validateStatus],
    headers: AxiosHeaders {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/1.2.2',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'get',
    url: 'http://35.200.198.232:9001/stake',
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'http:',
      path: '/stake',
      method: 'GET',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: '35.200.198.232',
      port: '9001',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/stake'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'GET /stake HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/1.2.2\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: 35.200.198.232:9001\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/stake',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '35.200.198.232',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'http://35.200.198.232:9001/stake',
    [Symbol(kCapture)]: false
  },
  cause: Error: connect ECONNREFUSED 35.200.198.232:9001
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '35.200.198.232',
    port: 9001
  }
}
AxiosError: read ECONNRESET
    at Function.AxiosError.from (/home/node/app/cli/node_modules/axios/dist/node/axios.cjs:789:14)
    at RedirectableRequest.handleRequestError (/home/node/app/cli/node_modules/axios/dist/node/axios.cjs:2744:25)
    at RedirectableRequest.emit (node:events:390:28)
    at ClientRequest.eventHandlers.<computed> (/home/node/app/cli/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:390:28)
    at Socket.socketErrorListener (node:_http_client:447:9)
    at Socket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  syscall: 'read',
  code: 'ECONNRESET',
  errno: -104,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: null },
    validateStatus: [Function: validateStatus],
    headers: AxiosHeaders {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/1.2.2',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'get',
    url: 'http://34.87.45.234:9001/account/a96760131ec1339c3591af3feec2d610c8f92035ce772222716bac55a45ff4f2?type=9',
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'http:',
      path: '/account/a96760131ec1339c3591af3feec2d610c8f92035ce772222716bac55a45ff4f2?type=9',
      method: 'GET',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: '34.87.45.234',
      port: '9001',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/account/a96760131ec1339c3591af3feec2d610c8f92035ce772222716bac55a45ff4f2',
      search: '?type=9'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'GET /account/a96760131ec1339c3591af3feec2d610c8f92035ce772222716bac55a45ff4f2?type=9 HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/1.2.2\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: 34.87.45.234:9001\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/account/a96760131ec1339c3591af3feec2d610c8f92035ce772222716bac55a45ff4f2?type=9',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '34.87.45.234',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'http://34.87.45.234:9001/account/a96760131ec1339c3591af3feec2d610c8f92035ce772222716bac55a45ff4f2?type=9',
    [Symbol(kCapture)]: false
  },
  cause: Error: read ECONNRESET
      at TCP.onStreamRead (node:internal/stream_base_commons:220:20) {
    errno: -104,
    code: 'ECONNRESET',
    syscall: 'read'
  }
}
```

![Zrzut ekranu z 2023-02-23 16-11-36](https://user-images.githubusercontent.com/116433520/220948168-4e8e9077-162c-4ef4-9d3a-0d4e87c4688c.png)

**Comment by bednarczyk9** [comment]
Log from Validator:

```shell
`validator > response is: {"newestCycle":{"activated":["193002d3d4995c747aedee2762633213ade363b91d68507878e2b58dc91230f6","8b7a571e9a31b4588ab8  │
│[ 1] validator             Mem:   0 MB    CPU:  0 %  stopped ││ validator > item is: {"newestCycle":{"activated":[],"activatedPublicKeys":[],"active":178,"apoptosized":["a57cdd487d8522f7e507d765db4a8d466f8b  │
│                                                             ││ validator > item is: {"newestCycle":{"activated":[],"activatedPublicKeys":[],"active":178,"apoptosized":["a57cdd487d8522f7e507d765db4a8d466f8b  │
│                                                             ││ validator > response is: {"newestCycle":{"activated":[],"activatedPublicKeys":[],"active":178,"apoptosized":["a57cdd487d8522f7e507d765db4a8d46  │
│                                                             ││ validator > item is: {"newestCycle":{"activated":[],"activatedPublicKeys":[],"active":166,"apoptosized":[],"counter":13407,"desired":150,"dura  │
│                                                             ││ validator > item is: {"newestCycle":{"activated":[],"activatedPublicKeys":[],"active":166,"apoptosized":[],"counter":13407,"desired":150,"dura  │
│                                                             ││ validator > response is: {"newestCycle":{"activated":[],"activatedPublicKeys":[],"active":166,"apoptosized":[],"counter":13407,"desired":150,"  │
│                                                             ││ validator > INJECTED_SET_CERT_TIME_TX {                                                                                                         │
│                                                             ││ validator >   success: true,                                                                                                                    │
│                                                             ││ validator >   reason: 'Transaction queued, poll for results.',                                                                                  │
│                                                             ││ validator >   status: 200                                                                                                                       │
│                                                             ││ validator > }                                                                                                                                   │
│                                                             ││ validator > item is: {"newestCycle":{"activated":[],"activatedPublicKeys":[],"active":156,"apoptosized":[],"counter":13408,"desired":180,"dura  │
│                                                             ││ validator > item is: {"newestCycle":{"activated":[],"activatedPublicKeys":[],"active":156,"apoptosized":[],"counter":13408,"desired":180,"dura  │
│                                                             ││ validator > response is: {"newestCycle":{"activated":[],"activatedPublicKeys":[],"active":156,"apoptosized":[],"counter":13408,"desired":180,"  │
│                                                             ││ validator > INJECTED_SET_CERT_TIME_TX {                                                                                                         │
│                                                             ││ validator >   success: true,                                                                                                                    │
│                                                             ││ validator >   reason: 'Transaction queued, poll for results.',                                                                                  │
│                                                             ││ validator >   status: 200                                                                                                                       │
│                                                             ││ validator > }                                                                                                                                   │
│                                                             ││ validator > item is: {"newestCycle":{"activated":["d57ab0bb9852ab15af13bc5766d13c933a2593a824ebc18017bc78e799364212"],"activatedPublicKeys":["  │
│                                                             ││ validator > item is: {"newestCycle":{"activated":["d57ab0bb9852ab15af13bc5766d13c933a2593a824ebc18017bc78e799364212"],"activatedPublicKeys":["  │
│                                                             ││ validator > response is: {"newestCycle":{"activated":["d57ab0bb9852ab15af13bc5766d13c933a2593a824ebc18017bc78e799364212"],"activatedPublicKeys  │
│                                                             ││ validator > stakeCert received. remainingValidTime / minimum time  534796 180000 expiredPercent: 0.10867333333333333, isExpiringSoon: false     │
│                                                             ││ validator > Error: Fatal: Join request Reason: IP or Port is not reachable                                                                      │
│                                                             ││ validator >     at evalmachine.<anonymous>:1:123130                                                                                             │
│                                                             ││ validator >     at runMicrotasks (<anonymous>)                                                                                                  │
│                                                             ││ validator >     at processTicksAndRejections (node:internal/process/task_queues:96:5)                                                           │
│                                                             ││ validator >     at x (evalmachine.<anonymous>:1:153723)                                                                                         │
│                                                             ││ validator >     at Object.startup (evalmachine.<anonymous>:1:155902)                                                                            │
│                                                             ││ validator >     at B.start (evalmachine.<anonymous>:1:194169)                                                                                   │
│                                                             ││ validator >     at /usr/src/app/src/index.ts:4885:5                                                                                             │
│                                                             ││ validator > Encountered a fatal error. Check fatal log for details.                                                                             │
│                                                             ││ validator > []                                                                                                                                  │
│                                                             ││ validator > []                                                                                                                                  │
│                                                             ││ validator > [] `
```

**Comment by Jamarox** [comment]
I had the same, that I tried to update node. After update, I can't remove stake.

**Comment by MarcusWentz** [comment]
Closing issue for now.

We can reopen the issue if it comes back or is still present.
