### ISSUE TITLE
Validator Error ```Problem with node operation, dashboard```

### ISSUE THREAD

**Issue by earningdose** [Shardeum/shardeum-bug-reporting#145]
##### What is the issue?

:red_circle:  Describe the error in simple terms. :red_circle: node works and turns itself off, the dashboard is not active

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle: 
![Untitled](https://user-images.githubusercontent.com/116700183/221453952-5f2ab6ed-0791-401f-90a6-1a46b5537e29.png)
![1](https://user-images.githubusercontent.com/116700183/221453954-9f084023-39b7-43d9-897a-a33ae750d9d2.png)

**Comment by serhiiqw** [comment]
-> the node works for 10 seconds and turns itself off, the dashboard is not active
->attempts to update the client, node, restart the node - did not help
![1](https://user-images.githubusercontent.com/95383379/221454584-8076241a-8c94-432e-a63d-ca57c24e679a.png)
![binare](https://user-images.githubusercontent.com/95383379/221454585-a93d7a96-8a90-44ff-a3b8-ab44c2fc08c4.png)
![Untitled](https://user-images.githubusercontent.com/95383379/221454586-60f4a258-18d3-4e98-98ed-dc8c36b7c20d.png)

**Comment by vanryan** [comment]
Same issue. Tried this in a couple of AZs as well. All in Ubuntu.

Error stack from cli -->


```
Error: Unable to fetch list of nodes in the network
    at getActiveNode (/home/node/app/cli/build/src/utils/fetch-network-data.js:43:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async fetchDataFromNetwork (/home/node/app/cli/build/src/utils/fetch-network-data.js:14:9)
    at async fetchEOADetails (/home/node/app/cli/build/src/utils/fetch-network-data.js:99:23)
    at async Command.<anonymous> (/home/node/app/cli/build/src/node-commands.js:218:29)
node@b65ed51d25e6:~/app$ operator-cli stake_info 0x4B75788A2fd34f68CfD727B8b4C74Ebdf976fF36
AxiosError: connect ECONNREFUSED 3.127.57.166:4000
    at Function.AxiosError.from (/home/node/app/cli/node_modules/axios/dist/node/axios.cjs:789:14)
    at RedirectableRequest.handleRequestError (/home/node/app/cli/node_modules/axios/dist/node/axios.cjs:2744:25)
    at RedirectableRequest.emit (node:events:390:28)
    at ClientRequest.eventHandlers.<computed> (/home/node/app/cli/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:390:28)
    at Socket.socketErrorListener (node:_http_client:447:9)
    at Socket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

...

Error: Unable to fetch list of nodes in the network
    at getActiveNode (/home/node/app/cli/build/src/utils/fetch-network-data.js:43:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async fetchDataFromNetwork (/home/node/app/cli/build/src/utils/fetch-network-data.js:14:9)
    at async fetchEOADetails (/home/node/app/cli/build/src/utils/fetch-network-data.js:99:23)
    at async Command.<anonymous> (/home/node/app/cli/build/src/node-commands.js:218:29)
```

**Comment by youngprogrammer11** [comment]
Empty dashboard

**Comment by Ankurpvt** [comment]
![Screenshot_2023-02-27-07-53-20-70_e4424258c8b8649f6e67d283a50a2cbc](https://user-images.githubusercontent.com/126367140/221457223-839682c7-0b54-42d3-9f5b-174f7fcac41c.jpg)


Empty Dashboard... Only error 🥺

**Comment by rainbowJson** [comment]
me too the problem

**Comment by rirasel55** [comment]
Dashboard empty

**Comment by huokoden** [comment]
My dashboard can't open why is this happening
![Screenshot_20230227-102320207](https://user-images.githubusercontent.com/36076679/221465654-e69f7e0e-e63f-4ad7-b5a7-a67845e8d8b3.jpg)
![Screenshot_20230227-095520521_1](https://user-images.githubusercontent.com/36076679/221465846-6c990e35-5fd1-47ab-8f8e-51688e36ab6c.jpg)

**Comment by ksbaskar** [comment]
seems all nodes went down. please rectify asap.
<img width="960" alt="se1" src="https://user-images.githubusercontent.com/6725456/221469522-dc2f6fb6-12c7-40a4-94a7-a07e9d2782df.png">
<img width="838" alt="se" src="https://user-images.githubusercontent.com/6725456/221469539-1dbd71bd-d6e7-4fd9-97ff-f9fec511919b.png">

**Comment by MASTAN82** [comment]
> me too the problem

me to same problem

**Comment by MASTAN82** [comment]
![Screenshot_2023-02-27-10-17-54-51_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/119680467/221478977-ef225ca4-7eef-48e5-b5e6-143d257025f8.jpg)

please help how to fix error

**Comment by bhanughai** [comment]
same issue

**Comment by AgataGolik** [comment]
The same issue. The node works for 10 seconds and turns itself off, I followed all the instructions (recommendations) it doesn't help anything....

**Comment by bigbri67** [comment]
> My dashboard can't open why is this happening ![Screenshot_20230227-102320207](https://user-images.githubusercontent.com/36076679/221465654-e69f7e0e-e63f-4ad7-b5a7-a67845e8d8b3.jpg) ![Screenshot_20230227-095520521_1](https://user-images.githubusercontent.com/36076679/221465846-6c990e35-5fd1-47ab-8f8e-51688e36ab6c.jpg)

**Comment by bigbri67** [comment]
me too, how to fix?

**Comment by 100405878** [comment]
I have the same problem, is it not solved yet?

**Comment by ravcha19** [comment]
Who could solve this? Help

**Comment by 100405878** [comment]
The testnet is down, to know exactly when it'll be fixed join the discord, but the developers estimate the next week
