### ISSUE TITLE
Validator Network Information error ```Cannot GET /load``` from ```http://<ip>:9001/load```

### ISSUE THREAD

**Issue by AndrewFucher** [Shardeum/shardeum-bug-reporting#200]
##### What is the issue?

`SOMETIMES`

When clicking `Network` page on gui I see blank page. Requests to fetch `network-stats`  returns 400 Bad Request
    
#### What impact does the issue have?

Cannot check network-stats when this happens. And I do not understand as a user why this happens.

##### How to reproduce the issue? 

Just launch node. At some point u will get to see this error

##### What other resources can you share regarding this issue?

Response from calling api `https://<ip>:8080/api/node/network`

```
{"errorMessage":"Unable to fetch version","errorDetails":"AxiosError: Request failed with status code 404\n    at settle (/home/node/app/cli/node_modules/axios/dist/node/axios.cjs:1859:12)\n    at IncomingMessage.handleStreamEnd (/home/node/app/cli/node_modules/axios/dist/node/axios.cjs:2723:11)\n    at IncomingMessage.emit (node:events:402:35)\n    at endReadableNT (node:internal/streams/readable:1343:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21) {\n  code: 'ERR_BAD_REQUEST',\n  config: {\n    transitional: {\n      silentJSONParsing: true,\n      forcedJSONParsing: true,\n      clarifyTimeoutError: false\n    },\n    adapter: [ 'xhr', 'http' ],\n    transformRequest: [ [Function: transformRequest] ],\n    transformResponse: [ [Function: transformResponse] ],\n    timeout: 0,\n    xsrfCookieName: 'XSRF-TOKEN',\n    xsrfHeaderName: 'X-XSRF-TOKEN',\n    maxContentLength: -1,\n    maxBodyLength: -1,\n    env: { FormData: [Function], Blob: null },\n    validateStatus: [Function: validateStatus],\n    headers: AxiosHeaders {\n      Accept: 'application/json, text/plain, */*',\n      'User-Agent': 'axios/1.2.2',\n      'Accept-Encoding': 'gzip, compress, deflate, br'\n    },\n    method: 'get',\n    url: 'http://127.0.0.1:9001/load',\n    data: undefined\n  },\n  request: <ref *1> ClientRequest {\n    _events: [Object: null prototype] {\n      abort: [Function (anonymous)],\n      aborted: [Function (anonymous)],\n      connect: [Function (anonymous)],\n      error: [Function (anonymous)],\n      socket: [Function (anonymous)],\n      timeout: [Function (anonymous)],\n      prefinish: [Function: requestOnPrefinish]\n    },\n    _eventsCount: 7,\n    _maxListeners: undefined,\n    outputData: [],\n    outputSize: 0,\n    writable: true,\n    destroyed: false,\n    _last: true,\n    chunkedEncoding: false,\n    shouldKeepAlive: false,\n    maxRequestsOnConnectionReached: false,\n    _defaultKeepAlive: true,\n    useChunkedEncodingByDefault: false,\n    sendDate: false,\n    _removedConnection: false,\n    _removedContLen: false,\n    _removedTE: false,\n    _contentLength: 0,\n    _hasBody: true,\n    _trailer: '',\n    finished: true,\n    _headerSent: true,\n    _closed: false,\n    socket: Socket {\n      connecting: false,\n      _hadError: false,\n      _parent: null,\n      _host: null,\n      _readableState: [ReadableState],\n      _events: [Object: null prototype],\n      _eventsCount: 7,\n      _maxListeners: undefined,\n      _writableState: [WritableState],\n      allowHalfOpen: false,\n      _sockname: null,\n      _pendingData: null,\n      _pendingEncoding: '',\n      server: null,\n      _server: null,\n      parser: null,\n      _httpMessage: [Circular *1],\n      [Symbol(async_id_symbol)]: 44,\n      [Symbol(kHandle)]: [TCP],\n      [Symbol(kSetNoDelay)]: false,\n      [Symbol(lastWriteQueueSize)]: 0,\n      [Symbol(timeout)]: null,\n      [Symbol(kBuffer)]: null,\n      [Symbol(kBufferCb)]: null,\n      [Symbol(kBufferGen)]: null,\n      [Symbol(kCapture)]: false,\n      [Symbol(kBytesRead)]: 0,\n      [Symbol(kBytesWritten)]: 0,\n      [Symbol(RequestTimeout)]: undefined\n    },\n    _header: 'GET /load HTTP/1.1\\r\\n' +\n      'Accept: application/json, text/plain, */*\\r\\n' +\n      'User-Agent: axios/1.2.2\\r\\n' +\n      'Accept-Encoding: gzip, compress, deflate, br\\r\\n' +\n      'Host: 127.0.0.1:9001\\r\\n' +\n      'Connection: close\\r\\n' +\n      '\\r\\n',\n    _keepAliveTimeout: 0,\n    _onPendingData: [Function: nop],\n    agent: Agent {\n      _events: [Object: null prototype],\n      _eventsCount: 2,\n      _maxListeners: undefined,\n      defaultPort: 80,\n      protocol: 'http:',\n      options: [Object: null prototype],\n      requests: [Object: null prototype] {},\n      sockets: [Object: null prototype],\n      freeSockets: [Object: null prototype] {},\n      keepAliveMsecs: 1000,\n      keepAlive: false,\n      maxSockets: Infinity,\n      maxFreeSockets: 256,\n      scheduling: 'lifo',\n      maxTotalSockets: Infinity,\n      totalSocketCount: 1,\n      [Symbol(kCapture)]: false\n    },\n    socketPath: undefined,\n    method: 'GET',\n    maxHeaderSize: undefined,\n    insecureHTTPParser: undefined,\n    path: '/load',\n    _ended: true,\n    res: IncomingMessage {\n      _readableState: [ReadableState],\n      _events: [Object: null prototype],\n      _eventsCount: 4,\n      _maxListeners: undefined,\n      socket: [Socket],\n      httpVersionMajor: 1,\n      httpVersionMinor: 1,\n      httpVersion: '1.1',\n      complete: true,\n      rawHeaders: [Array],\n      rawTrailers: [],\n      aborted: false,\n      upgrade: false,\n      url: '',\n      method: null,\n      statusCode: 404,\n      statusMessage: 'Not Found',\n      client: [Socket],\n      _consuming: false,\n      _dumped: false,\n      req: [Circular *1],\n      responseUrl: 'http://127.0.0.1:9001/load',\n      redirects: [],\n      [Symbol(kCapture)]: false,\n      [Symbol(kHeaders)]: [Object],\n      [Symbol(kHeadersCount)]: 16,\n      [Symbol(kTrailers)]: null,\n      [Symbol(kTrailersCount)]: 0,\n      [Symbol(RequestTimeout)]: undefined\n    },\n    aborted: false,\n    timeoutCb: null,\n    upgradeOrConnect: false,\n    parser: null,\n    maxHeadersCount: null,\n    reusedSocket: false,\n    host: '127.0.0.1',\n    protocol: 'http:',\n    _redirectable: Writable {\n      _writableState: [WritableState],\n      _events: [Object: null prototype],\n      _eventsCount: 3,\n      _maxListeners: undefined,\n      _options: [Object],\n      _ended: true,\n      _ending: true,\n      _redirectCount: 0,\n      _redirects: [],\n      _requestBodyLength: 0,\n      _requestBodyBuffers: [],\n      _onNativeResponse: [Function (anonymous)],\n      _currentRequest: [Circular *1],\n      _currentUrl: 'http://127.0.0.1:9001/load',\n      [Symbol(kCapture)]: false\n    },\n    [Symbol(kCapture)]: false,\n    [Symbol(kNeedDrain)]: false,\n    [Symbol(corked)]: 0,\n    [Symbol(kOutHeaders)]: [Object: null prototype] {\n      accept: [Array],\n      'user-agent': [Array],\n      'accept-encoding': [Array],\n      host: [Array]\n    }\n  },\n  response: {\n    status: 404,\n    statusText: 'Not Found',\n    headers: AxiosHeaders {\n      'x-powered-by': 'Express',\n      'access-control-allow-origin': '*',\n      'content-security-policy': \"default-src 'none'\",\n      'x-content-type-options': 'nosniff',\n      'content-type': 'text/html; charset=utf-8',\n      'content-length': '143',\n      date: 'Thu, 09 Mar 2023 10:58:58 GMT',\n      connection: 'close'\n    },\n    config: {\n      transitional: [Object],\n      adapter: [Array],\n      transformRequest: [Array],\n      transformResponse: [Array],\n      timeout: 0,\n      xsrfCookieName: 'XSRF-TOKEN',\n      xsrfHeaderName: 'X-XSRF-TOKEN',\n      maxContentLength: -1,\n      maxBodyLength: -1,\n      env: [Object],\n      validateStatus: [Function: validateStatus],\n      headers: [AxiosHeaders],\n      method: 'get',\n      url: 'http://127.0.0.1:9001/load',\n      data: undefined\n    },\n    request: <ref *1> ClientRequest {\n      _events: [Object: null prototype],\n      _eventsCount: 7,\n      _maxListeners: undefined,\n      outputData: [],\n      outputSize: 0,\n      writable: true,\n      destroyed: false,\n      _last: true,\n      chunkedEncoding: false,\n      shouldKeepAlive: false,\n      maxRequestsOnConnectionReached: false,\n      _defaultKeepAlive: true,\n      useChunkedEncodingByDefault: false,\n      sendDate: false,\n      _removedConnection: false,\n      _removedContLen: false,\n      _removedTE: false,\n      _contentLength: 0,\n      _hasBody: true,\n      _trailer: '',\n      finished: true,\n      _headerSent: true,\n      _closed: false,\n      socket: [Socket],\n      _header: 'GET /load HTTP/1.1\\r\\n' +\n        'Accept: application/json, text/plain, */*\\r\\n' +\n        'User-Agent: axios/1.2.2\\r\\n' +\n        'Accept-Encoding: gzip, compress, deflate, br\\r\\n' +\n        'Host: 127.0.0.1:9001\\r\\n' +\n        'Connection: close\\r\\n' +\n        '\\r\\n',\n      _keepAliveTimeout: 0,\n      _onPendingData: [Function: nop],\n      agent: [Agent],\n      socketPath: undefined,\n      method: 'GET',\n      maxHeaderSize: undefined,\n      insecureHTTPParser: undefined,\n      path: '/load',\n      _ended: true,\n      res: [IncomingMessage],\n      aborted: false,\n      timeoutCb: null,\n      upgradeOrConnect: false,\n      parser: null,\n      maxHeadersCount: null,\n      reusedSocket: false,\n      host: '127.0.0.1',\n      protocol: 'http:',\n      _redirectable: [Writable],\n      [Symbol(kCapture)]: false,\n      [Symbol(kNeedDrain)]: false,\n      [Symbol(corked)]: 0,\n      [Symbol(kOutHeaders)]: [Object: null prototype]\n    },\n    data: '<!DOCTYPE html>\\n' +\n      '<html lang=\"en\">\\n' +\n      '<head>\\n' +\n      '<meta charset=\"utf-8\">\\n' +\n      '<title>Error</title>\\n' +\n      '</head>\\n' +\n      '<body>\\n' +\n      '<pre>Cannot GET /load</pre>\\n' +\n      '</body>\\n' +\n      '</html>\\n'\n  }\n}\n"}
```

Response from calling  http://<ip>:9001/load 

```Cannot GET /load```

**Comment by MarcusWentz** [comment]
Does https://<ip>:9001/load show the same error?

**Comment by AndrewFucher** [comment]
No. It does not show error of that sort. Right now I cannot reproduce error described earlier but neverless when I use GET request on `https://<ip>:9001/load` it returns me WRONG_VERSION_NUMBER (python, requests). In browser it just shows wrong ERR_SSL_PROTOCOL_ERROR

**Comment by MarcusWentz** [comment]
Q1. Are you able to stake and unstake from the Validator CLI:

https://docs.shardeum.org/node/run/validator#cli

?

Q2. Do you have a screenshot for the error you see with:

https://<ip>:9001/load 

?

**Comment by AndrewFucher** [comment]
A1: I am **able** to unstake via Validator CLI (terminal) and staking also works (sometimes there are error `Maximum load exceeded`).

A2: I do not have screenshot. But as I mentioned it in description: It just says text `Cannot GET /load`. Nothing else.

**Comment by swarna1101** [comment]
The issue has been thoroughly investigated and resolved.
