### ISSUE TITLE
Validator GUI Web Console Error `invalid BigNumber string`

### ISSUE THREAD

**Issue by nControl88** [Shardeum/shardeum-bug-reporting#223]
##### What is the issue?

Opening the Maintenance page, the following two errors appears in the web console:
```javascript
`maintenance-face70c8e9c942e6.js:1          
GET https://xxx.xxx.xxx.xx:8080/api/account/0x231xxx/stakeInfo 400 (Bad Request)`
```
and
```javascript
`Error: invalid BigNumber string (argument="value", value="1.025e+21", code=INVALID_ARGUMENT, version=bignumber/5.7.0)
    at Logger.makeError (/home/node/app/cli/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/home/node/app/cli/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at Logger.throwArgumentError (/home/node/app/cli/node_modules/@ethersproject/logger/lib/index.js:250:21)
    at Function.BigNumber.from (/home/node/app/cli/node_modules/@ethersproject/bignumber/lib/bignumber.js:199:27)
    at formatFixed (/home/node/app/cli/node_modules/@ethersproject/bignumber/lib/fixednumber.js:43:35)
    at formatUnits (/home/node/app/cli/node_modules/@ethersproject/units/lib/index.js:67:40)
    at Object.formatEther (/home/node/app/cli/node_modules/@ethersproject/units/lib/index.js:84:12)
    at Command.<anonymous> (/home/node/app/cli/build/src/node-commands.js:210:46)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'invalid BigNumber string',
  code: 'INVALID_ARGUMENT',
  argument: 'value',
  value: '1.025e+21'
}`
```

#### What impact does the issue have?

SHM stake shown is incorrect. Showing as `-`

##### How to reproduce the issue? 

Opening the Maintenance page. Error is still present after emptying cache and hard reload

**Comment by swarna1101** [comment]
The issue with the Maintenance page displaying errors in the console has been fixed in our latest update. The errors related to a bad request for stake information and the incorrect BigNumber format have been addressed. Users should now see the correct SHM stake information on the Maintenance page. Please ensure your cache is cleared and perform a hard reload to experience the changes.
