### ISSUE TITLE
Validator GUI Connected Wallet Address Does Not Appear

### ISSUE THREAD

**Issue by undecesjours** [Shardeum/shardeum-bug-reporting#224]
Hi, my node is running fine :)

I just have this problem (connected to Metamask)
![image](https://user-images.githubusercontent.com/127980910/226070662-cc37fc5e-cd24-4012-b3f9-2b18d14763cd.png)
My stake adress is not displayed, and transactions fail on Metamask.

Could you help please ?

**Comment by MarcusWentz** [comment]
Which browser are you using?

**Comment by undecesjours** [comment]
Hi,
Chrome. I already tried with Edge, it is the same problem:
![image](https://user-images.githubusercontent.com/127980910/226072685-d9c272ce-ddc0-4dd7-8037-fbaa2e9732ff.png)

**Comment by MarcusWentz** [comment]
Which transaction is failing exactly for the Validator?

**Comment by undecesjours** [comment]
both staking and unstaking 10 SHM with GUI

**Comment by MarcusWentz** [comment]
Can you transfer SHM between wallets?

**Comment by undecesjours** [comment]
Hi,
Yes it works,...
By the way, I tried ro reinstall Chrome (and Metamask), i'm yet unable to connect to the GUI, the password is not recognized, but it still works on Edge ....
Far too many bugs, ... it is getting hard.
I think i'm gonna try the process described in the doc with the CLI commands to set up my private key to stake and unstake.
Thanks for your help

**Comment by MarcusWentz** [comment]
We will have a Validator update soon with password bug fixes.

**Comment by undecesjours** [comment]
Hi,

It is very strange, i had still 0 credits, but i tried and tried again to stake, and finally, it worked !!! and my credits reappeared !

PS : after 1( min, the credit s still diseapper... i don't understand anything, but the stake is here 👍 

Do you have any idea of what happen ? i allready have reinstalled Chrome and Metamask
![image](https://user-images.githubusercontent.com/127980910/227862697-4351703b-15dd-405a-a140-5accf9cf78dc.png)
![image](https://user-images.githubusercontent.com/127980910/227862777-7397e848-f197-4565-8939-461e6a6ea377.png)

Here are my logs :
[2023-03-25T20:13:15.346] [INFO] main - Logger initialized.
[2023-03-25T20:13:17.163] [WARN] main - Failed to get external IP from gateway: UPnP get external failed
[2023-03-25T20:13:17.591] [INFO] main - Network: External server running on port 9001...
[2023-03-25T20:13:22.626] [INFO] main - Keypair loaded from file secrets.json
[2023-03-25T21:52:41.778] [INFO] main - Stopping reporter...
[2023-03-25T21:52:41.778] [INFO] main - Stopping statistics reporting...
[2023-03-25T21:52:41.778] [INFO] main - Stopping POW generators...
[2023-03-25T21:52:41.778] [INFO] main - Shutting down p2p...
[2023-03-25T21:52:41.781] [INFO] main - Shutting down the application...
[2023-03-25T21:52:41.782] [INFO] main - Shutting down networking...
[2023-03-25T21:52:41.782] [INFO] main - Closing Database connections...
[2023-03-25T21:52:41.782] [INFO] main - Shutting down logs...
[2023-03-25T21:52:57.714] [INFO] main - Logger initialized.
[2023-03-25T21:52:59.530] [WARN] main - Failed to get external IP from gateway: UPnP get external failed
[2023-03-25T21:52:59.978] [INFO] main - Network: External server running on port 9001...
[2023-03-25T21:53:05.012] [INFO] main - Keypair loaded from file secrets.json

Thank you very much !

**Comment by undecesjours** [comment]
Hi,

and i have this errors in the p2P.log 
[2023-03-27T21:41:40.611] [WARN] p2p - Self: Error while joining network:
[2023-03-27T21:41:40.611] [WARN] p2p - Self: Error: Bad response
[2023-03-27T21:41:40.611] [WARN] p2p - Self: Error: Bad response
    at Object.R [as getNewestCycle] (evalmachine.<anonymous>:1:164280)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at x (evalmachine.<anonymous>:1:155885)
    at Object.startup (evalmachine.<anonymous>:1:159112)
    at B.start (evalmachine.<anonymous>:1:198161)
    at /usr/src/app/src/index.ts:5096:5
[2023-03-27T21:43:08.509] [WARN] p2p - Self: Error while joining network:
[2023-03-27T21:43:08.509] [WARN] p2p - Self: TimeoutError: Timeout awaiting 'request' for 1000ms
[2023-03-27T21:43:08.510] [WARN] p2p - Self: TimeoutError: Timeout awaiting 'request' for 1000ms
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/got/source/request-as-event-emitter.js:176:14)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:402:35)
    at ClientRequest.origin.emit (/usr/src/app/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at Immediate.timeoutHandler (/usr/src/app/node_modules/got/source/utils/timed-out.js:63:11)
    at processImmediate (node:internal/timers:466:21)
