### ISSUE TITLE
Validator Errors `p2p - Self: Error while joining network` and `p2p - Self: Error: Node not ready to join`

### ISSUE THREAD

**Issue by senkiss** [Shardeum/shardeum-bug-reporting#225]
[2023-03-18T00:40:21.978] [INFO] p2p - HELLO
[2023-03-18T00:40:21.979] [INFO] p2p - Active: Sync time records sorted 0 []
[2023-03-18T00:40:27.659] [WARN] p2p - Self: Error while joining network:
[2023-03-18T00:40:27.660] [WARN] p2p - Self: Error: Node not ready to join
[2023-03-18T00:40:27.662] [WARN] p2p - Self: Error: Node not ready to join
    at x (evalmachine.<anonymous>:1:153146)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.startup (evalmachine.<anonymous>:1:155902)
    at B.start (evalmachine.<anonymous>:1:194169)
    at /usr/src/app/src/index.ts:4867:5
[2023-03-18T00:41:29.483] [WARN] p2p - Self: Error while joining network:
[2023-03-18T00:41:29.483] [WARN] p2p - Self: Error: Node not ready to join
[2023-03-18T00:41:29.485] [WARN] p2p - Self: Error: Node not ready to join
    at x (evalmachine.<anonymous>:1:153146)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.startup (evalmachine.<anonymous>:1:155902)
    at B.start (evalmachine.<anonymous>:1:194169)
    at /usr/src/app/src/index.ts:4867:5
[2023-03-18T00:42:36.646] [WARN] p2p - Self: Error while joining network:
[2023-03-18T00:42:36.646] [WARN] p2p - Self: Error: Node not ready to join
[2023-03-18T00:42:36.648] [WARN] p2p - Self: Error: Node not ready to join
    at x (evalmachine.<anonymous>:1:153146)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.startup (evalmachine.<anonymous>:1:155902)
    at B.start (evalmachine.<anonymous>:1:194169)
    at /usr/src/app/src/index.ts:4867:5
[2023-03-18T00:43:39.053] [WARN] p2p - Self: Error while joining network:
[2023-03-18T00:43:39.053] [WARN] p2p - Self: Error: Node not ready to join
[2023-03-18T00:43:39.054] [WARN] p2p - Self: Error: Node not ready to join
    at x (evalmachine.<anonymous>:1:153146)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.startup (evalmachine.<anonymous>:1:155902)
    at B.start (evalmachine.<anonymous>:1:194169)
    at /usr/src/app/src/index.ts:4867:5
[2023-03-18T00:44:45.265] [WARN] p2p - Self: Error while joining network:
[2023-03-18T00:44:45.265] [WARN] p2p - Self: Error: Node not ready to join
[2023-03-18T00:44:45.265] [WARN] p2p - Self: Error: Node not ready to join
    at x (evalmachine.<anonymous>:1:153146)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.startup (evalmachine.<anonymous>:1:155902)
    at B.start (evalmachine.<anonymous>:1:194169)
    at /usr/src/app/src/index.ts:4867:5
[2023-03-18T00:45:48.480] [WARN] p2p - Self: Error while joining network:
[2023-03-18T00:45:48.480] [WARN] p2p - Self: Error: Node not ready to join
[2023-03-18T00:45:48.481] [WARN] p2p - Self: Error: Node not ready to join
    at x (evalmachine.<anonymous>:1:153146)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.startup (evalmachine.<anonymous>:1:155902)
    at B.start (evalmachine.<anonymous>:1:194169)
    at /usr/src/app/src/index.ts:4867:5
[2023-03-18T00:46:51.677] [WARN] p2p - Self: Error while joining network:
[2023-03-18T00:46:51.677] [WARN] p2p - Self: Error: Node not ready to join
[2023-03-18T00:46:51.677] [WARN] p2p - Self: Error: Node not ready to join
    at x (evalmachine.<anonymous>:1:153146)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.startup (evalmachine.<anonymous>:1:155902)
    at B.start (evalmachine.<anonymous>:1:194169)
    at /usr/src/app/src/index.ts:4867:5
[2023-03-18T00:47:57.465] [WARN] p2p - Self: Error while joining network:
[2023-03-18T00:47:57.465] [WARN] p2p - Self: Error: Node not ready to join
[2023-03-18T00:47:57.466] [WARN] p2p - Self: Error: Node not ready to join
    at x (evalmachine.<anonymous>:1:153146)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.startup (evalmachine.<anonymous>:1:155902)
    at B.start (evalmachine.<anonymous>:1:194169)
    at /usr/src/app/src/index.ts:4867:5
[2023-03-18T00:49:02.703] [WARN] p2p - Self: Error while joining network:
[2023-03-18T00:49:02.703] [WARN] p2p - Self: Error: Node not ready to join
[2023-03-18T00:49:02.705] [WARN] p2p - Self: Error: Node not ready to join
    at x (evalmachine.<anonymous>:1:153146)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.startup (evalmachine.<anonymous>:1:155902)
    at B.start (evalmachine.<anonymous>:1:194169)
    at /usr/src/app/src/index.ts:4867:5
[2023-03-18T00:50:04.687] [WARN] p2p - Self: Error while joining network:
[2023-03-18T00:50:04.687] [WARN] p2p - Self: Error: Node not ready to join
[2023-03-18T00:50:04.689] [WARN] p2p - Self: Error: Node not ready to join
    at x (evalmachine.<anonymous>:1:153146)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.startup (evalmachine.<anonymous>:1:155902)
    at B.start (evalmachine.<anonymous>:1:194169)
    at /usr/src/app/src/index.ts:4867:5
[2023-03-18T00:51:10.116] [WARN] p2p - Self: Error while joining network:
[2023-03-18T00:51:10.116] [WARN] p2p - Self: Error: Node not ready to join
[2023-03-18T00:51:10.116] [WARN] p2p - Self: Error: Node not ready to join
    at x (evalmachine.<anonymous>:1:153146)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.startup (evalmachine.<anonymous>:1:155902)
    at B.start (evalmachine.<anonymous>:1:194169)
    at /usr/src/app/src/index.ts:4867:5
[2023-03-18T00:53:24.987] [WARN] p2p - Self: Error while joining network:
[2023-03-18T00:53:24.988] [WARN] p2p - Self: TimeoutError: Timeout awaiting 'request' for 1000ms
[2023-03-18T00:53:24.995] [WARN] p2p - Self: TimeoutError: Timeout awaiting 'request' for 1000ms
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/got/source/request-as-event-emitter.js:176:14)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:402:35)
    at ClientRequest.origin.emit (/usr/src/app/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at Immediate.timeoutHandler (/usr/src/app/node_modules/got/source/utils/timed-out.js:63:11)
    at processImmediate (node:internal/timers:466:21)
[2023-03-18T00:55:24.506] [WARN] p2p - Self: Error while joining network:
[2023-03-18T00:55:24.507] [WARN] p2p - Self: TimeoutError: Timeout awaiting 'request' for 1000ms
[2023-03-18T00:55:24.507] [WARN] p2p - Self: TimeoutError: Timeout awaiting 'request' for 1000ms
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/got/source/request-as-event-emitter.js:176:14)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:402:35)
    at ClientRequest.origin.emit (/usr/src/app/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at Immediate.timeoutHandler (/usr/src/app/node_modules/got/source/utils/timed-out.js:63:11)
    at processImmediate (node:internal/timers:466:21)
[2023-03-18T00:56:27.228] [WARN] p2p - Self: Error while joining network:
[2023-03-18T00:56:27.229] [WARN] p2p - Self: Error: Node not ready to join
[2023-03-18T00:56:27.230] [WARN] p2p - Self: Error: Node not ready to join
    at x (evalmachine.<anonymous>:1:153146)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.startup (evalmachine.<anonymous>:1:155902)
    at B.start (evalmachine.<anonymous>:1:194169)
    at /usr/src/app/src/index.ts:4867:5
[2023-03-18T00:57:32.067] [WARN] p2p - Self: Error while joining network:
[2023-03-18T00:57:32.067] [WARN] p2p - Self: Error: Node not ready to join
[2023-03-18T00:57:32.068] [WARN] p2p - Self: Error: Node not ready to join
    at x (evalmachine.<anonymous>:1:153146)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.startup (evalmachine.<anonymous>:1:155902)
    at B.start (evalmachine.<anonymous>:1:194169)
    at /usr/src/app/src/index.ts:4867:5

**Comment by MarcusWentz** [comment]
Do you have a GUI or CLI screenshot for the error?

**Comment by senkiss** [comment]
> Do you have a GUI or CLI screenshot for the error?
[2023-03-18T01:12:23.761] [WARN] p2p - Self: Error while joining network:
[2023-03-18T01:12:23.761] [WARN] p2p - Self: RequestError: connect ECONNREFUSED 43.131.45.50:9001
[2023-03-18T01:12:23.761] [WARN] p2p - Self: RequestError: connect ECONNREFUSED 43.131.45.50:9001

![4444](https://user-images.githubusercontent.com/30034652/226076058-7dcfb6c1-3095-4583-b884-9354abf3ec3e.png)
![555](https://user-images.githubusercontent.com/30034652/226076281-8a15b8cc-1195-47b1-ba8e-1bea90edb107.png)


![6666](https://user-images.githubusercontent.com/30034652/226076284-7a6abb2c-4db1-46b0-ac6d-497f7ad02fb2.png)
![7777](https://user-images.githubusercontent.com/30034652/226076288-1aecabd5-fa67-4a0f-a13f-2eff28c7f91c.png)

**Comment by senkiss** [comment]
The node status always standby but internet connection is ver well!

**Comment by MarcusWentz** [comment]
The time to be added as an active validator will vary based on network load and validators in the network.

https://github.com/Shardeum/shardeum-bug-reporting/issues/60

**Comment by Burekas** [comment]
**Having the same issue:**

_[2023-04-08T11:10:07.270] [WARN] p2p - Self: Error while joining network:
[2023-04-08T11:10:07.271] [WARN] p2p - Self: Error: Node not ready to join
[2023-04-08T11:10:07.271] [WARN] p2p - Self: Error: Node not ready to join
    at x (evalmachine.<anonymous>:1:156475)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.startup (evalmachine.<anonymous>:1:159599)
    at B.start (evalmachine.<anonymous>:1:198648)
    at /usr/src/app/src/index.ts:5163:5
[2023-04-08T11:11:12.537] [WARN] p2p - Self: Error while joining network:
[2023-04-08T11:11:12.537] [WARN] p2p - Self: Error: Node not ready to join
[2023-04-08T11:11:12.539] [WARN] p2p - Self: Error: Node not ready to join
    at x (evalmachine.<anonymous>:1:156475)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.startup (evalmachine.<anonymous>:1:159599)
    at B.start (evalmachine.<anonymous>:1:198648)
    at /usr/src/app/src/index.ts:5163:5
[2023-04-08T11:12:18.155] [WARN] p2p - Self: Error while joining network:
[2023-04-08T11:12:18.155] [WARN] p2p - Self: Error: Node not ready to join
[2023-04-08T11:12:18.155] [WARN] p2p - Self: Error: Node not ready to join
    at x (evalmachine.<anonymous>:1:156475)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.startup (evalmachine.<anonymous>:1:159599)
    at B.start (evalmachine.<anonymous>:1:198648)
    at /usr/src/app/src/index.ts:5163:5
[2023-04-08T11:13:20.352] [WARN] p2p - Self: Error while joining network:
[2023-04-08T11:13:20.352] [WARN] p2p - Self: Error: Node not ready to join
[2023-04-08T11:13:20.352] [WARN] p2p - Self: Error: Node not ready to join
    at x (evalmachine.<anonymous>:1:156475)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.startup (evalmachine.<anonymous>:1:159599)
    at B.start (evalmachine.<anonymous>:1:198648)
    at /usr/src/app/src/index.ts:5163:5_
    
**Nodeinfo from remote machine(:port/nodeinfo):**
    `{"nodeInfo":{"publicKey":"5f14efa6a88622843321541f2f10bbcaa1fee7ebe372333aeaa0e76f62859112","curvePublicKey":"632e8d6299aa28f0a51484cf17c020ef41ecdb9f72755c68ab7d309634672633","externalIp":"xxx.xxx.255.zz","externalPort":10001,"internalIp":"xxx.xxx.255.zz","internalPort":11001,"status":null,"appData":{"shardeumVersion":"1.1.6","minVersion":"","activeVersion":"","latestVersion":""}}}`

**operator-cli status:**
_state: standby
totalTimeRunning: 155535.213
totalTimeValidating: '00:00:00'
lastActive: ''
lastRotationIndex: ''
stakeRequirement: '10.0'
nominatorAddress: '0xsss'
nomineeAddress: 5f14efa6sss
performance:
  memPercentage: 17.827195281478623
  diskPercentage: 2.9068636498178106
  cpuPercentage: 2.368866328257191
currentRewards: '0.0'
lockedStake: '25.0'
nodeInfo: ''_

**main.log:**
_[2023-04-06T16:12:28.605] [INFO] main - Logger initialized.
[2023-04-06T16:12:30.430] [WARN] main - Failed to get external IP from gateway: UPnP get external failed
[2023-04-06T16:12:30.701] [INFO] main - Network: External server running on port 10001...
[2023-04-06T16:12:30.713] [INFO] main - Unable to load keypair. Generating new...
[2023-04-06T16:12:30.713] [INFO] main - New keypair generated.
[2023-04-06T16:12:30.714] [INFO] main - New keypair successfully generated and saved to database._
    
**SHM Staked, Ports are open, Interal/extarnal Ip is correct. Most other logs are empty(error, fatal, exit). The only issue is in p2p log**

<img width="1164" alt="Screen Shot 2023-04-08 at 14 23 30" src="https://user-images.githubusercontent.com/2567471/230718839-492625b0-1d43-4eed-9d4f-53c4f0476e7a.png">

**Comment by amineDev** [comment]
I'm getting the same error on p2p.log after upgrading from 1.1.6 to 1.1.7 :

```
[2023-04-21T19:00:16.634] [WARN] p2p - Self: Error while joining network:
[2023-04-21T19:00:16.634] [WARN] p2p - Self: Error: Node not ready to join
[2023-04-21T19:00:16.635] [WARN] p2p - Self: Error: Node not ready to join
    at x (evalmachine.<anonymous>:1:156819)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.startup (evalmachine.<anonymous>:1:160336)
    at Q.start (evalmachine.<anonymous>:1:199540)
    at /usr/src/app/src/index.ts:5286:5
[2023-04-21T19:01:19.448] [WARN] p2p - Self: Error while joining network:
[2023-04-21T19:01:19.448] [WARN] p2p - Self: Error: Node not ready to join
[2023-04-21T19:01:19.449] [WARN] p2p - Self: Error: Node not ready to join
    at x (evalmachine.<anonymous>:1:156819)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.startup (evalmachine.<anonymous>:1:160336)
    at Q.start (evalmachine.<anonymous>:1:199540)
    at /usr/src/app/src/index.ts:5286:5
[2023-04-21T19:03:08.506] [WARN] p2p - Self: Error while joining network:
[2023-04-21T19:03:08.506] [WARN] p2p - Self: TimeoutError: Timeout awaiting 'request' for 1000ms
[2023-04-21T19:03:08.506] [WARN] p2p - Self: TimeoutError: Timeout awaiting 'request' for 1000ms
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/got/source/request-as-event-emitter.js:176:14)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:402:35)
    at ClientRequest.origin.emit (/usr/src/app/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at Immediate.timeoutHandler (/usr/src/app/node_modules/got/source/utils/timed-out.js:63:11)
    at processImmediate (node:internal/timers:466:21)
```

@MarcusWentz Any update please ?

BR

**Comment by willfadeneva** [comment]
New ubuntu install, tried to install 3rd time, node successful, staking looks good but on logs i see errors, last time i ran node for a week it didnt give me any rewards
[2023-05-31T02:35:37.506] [WARN] p2p - Self: Error while joining network:
[2023-05-31T02:35:37.506] [WARN] p2p - Self: TimeoutError: Timeout awaiting 'request' for 1000ms
[2023-05-31T02:35:37.506] [WARN] p2p - Self: TimeoutError: Timeout awaiting 'request' for 1000ms
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/got/source/request-as-event-emitter.js:176:14)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:402:35)
    at ClientRequest.origin.emit (/usr/src/app/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at Immediate.timeoutHandler (/usr/src/app/node_modules/got/source/utils/timed-out.js:63:11)
    at processImmediate (node:internal/timers:466:21)
![image](https://github.com/Shardeum/shardeum-bug-reporting/assets/77789235/174afd1c-e08d-4044-a289-2a99f1669323)

**Comment by willfadeneva** [comment]
Has anyone looked at this bug. My node was active for 10 days and finally I shut it down. Today I did a fresh reinstall again but same issue.

**Comment by likemusic** [comment]
The same:

```
CLI/GUI Running Version: 1.2.1 / 1.2.0
CLI/GUI Latest Version: 1.2.1 / 1.2.0
Validator Running Version: 1.4.0
Active Network Version: 1.4.0
Validator Minimum Version: 1.4.0
```


```
[2023-06-19T08:17:17.038] [INFO] p2p - Active: Median sync time at cycle 17808 is 297 s.
[2023-06-19T08:17:17.330] [INFO] p2p - Apoptosis: check if the node is apop marked node 43272ab95d3e4b9a05ee1e72613d3993441f0b554bd94b32165c77e929c4e432 false
[2023-06-19T08:17:17.331] [ERROR] p2p - Comms: P2P: ask: network.ask: Error: Request timed out. "key_get_account_data_with_queue_hints_7f19x28572_1687162632328_33356"
[2023-06-19T09:58:55.544] [INFO] p2p - HELLO
[2023-06-19T09:58:55.545] [INFO] p2p - Active: Sync time records sorted 0 []
[2023-06-19T09:58:56.054] [WARN] p2p - Self: Error while joining network:
[2023-06-19T09:58:56.054] [WARN] p2p - Self: Error: Node not ready to join
[2023-06-19T09:58:56.056] [WARN] p2p - Self: Error: Node not ready to join
    at T (evalmachine.<anonymous>:1:160235)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.startup (evalmachine.<anonymous>:1:163892)
    at async U.start (evalmachine.<anonymous>:1:206901)
    at async /usr/src/app/dist/src/index.js:4722:9
[2023-06-19T09:59:57.896] [WARN] p2p - Self: Error while joining network:
[2023-06-19T09:59:57.897] [WARN] p2p - Self: Error: Node not ready to join
[2023-06-19T09:59:57.897] [WARN] p2p - Self: Error: Node not ready to join
    at T (evalmachine.<anonymous>:1:160235)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.startup (evalmachine.<anonymous>:1:163892)
    at async U.start (evalmachine.<anonymous>:1:206901)
    at async /usr/src/app/dist/src/index.js:4722:9
```

**Comment by willfadeneva** [comment]
Well seems like I gotta let this go.

**Comment by swarna1101** [comment]
this issue has been successfully resolved in the latest version of our network.
![image](https://github.com/Shardeum/shardeum-bug-reporting/assets/113277972/69c5e87a-1a8f-4a43-b8d4-c47d009d2a6b)
