### ISSUE TITLE
RPC  ```get_transaction(tx_hash)``` deserialization error

### ISSUE THREAD

**Issue by MarcusWentz** [Shardeum/shardeum-bug-reporting#24]
##### What is the issue?

Cannot read transaction parameters from RPC  ```get_transaction(tx_hash)```:

```shell
Error: Deserialization Error: invalid type: integer `672`, 
expected a (both 0x-prefixed or not) hex string or byte 
array containing between (0; 32] bytes at line 1 column 310. 
Response: {"blockHash":"0x2edf13594482e0a9e651546646d648b1a30afcb5c7b94e774524d77b4eafd9ae",
"blockNumber":"0x6d267","from":"0xc1202e7d42655f23097476f6d48006fe56d38d4f","gas":"0x5208",
"gasPrice":"0x4a817c800","hash":"0xc0478ea8a26fa562ea8ff6640f2090ac8fa075704bb5f973ab0448a1f2ac22c3",
"input":"0x68656c6c6f21","nonce":672,"to":"0x66c1d8a5ee726b545576a75380391835f8aaa43c",
"transactionIndex":"0x1","value":"8ac7230489e80000","v":"0x25",
"r":"0x1b5e176d927f8e9ab405058b2d2457392da3e20f328b16ddabcebc33eaac5fea",
"s":"0x4ba69724e8f69de52f0125ad8b3c5c2cef33019bac3249e2c0a2192766d1721c",
"contractAddress":null,"data":"0x"}
```
    
#### What impact does the issue have?

Unable to read transaction parameters directly since the script crashes with this error.

##### How to reproduce the issue? 

Rust script with Goerli working but Liberty 2.1 has deserialization issue:

```rust
use std::convert::TryFrom;
// use std::env;

use ethers_providers::{Middleware, Provider, Http};
use ethers_core::types::{H256,U256};
// use ethers_core::types::{Address,H256,U256};

use eyre::Result;

#[tokio::main]
async fn main() -> Result<()> {

    // let rpc_goerli_infura_https = env::var("goerliHTTPS_InfuraAPIKey").expect("$goerliHTTPS_InfuraAPIKey is not set");

    // let provider = Provider::<Http>::try_from(rpc_goerli_infura_https).expect("could not instantiate HTTP Provider");

    let rpc_shardeum_https = "https://liberty20.shardeum.org/";

    let provider = Provider::<Http>::try_from(rpc_shardeum_https).expect("could not instantiate HTTP Provider");

    let chainid = provider.get_chainid().await?;
    println!("Got chainid: {}", chainid);

    let current_block_number = provider.get_block_number().await?;
    println!("current_block_number: {:?}", current_block_number);
    
    let current_block_parameters = provider.get_block(current_block_number).await?;
    println!(" current_block_parameters: {:?}", current_block_parameters);

    if chainid == U256::from(5) { //Goerli
        let tx_hash = "0x7bd590a4c9100402fb105f7de66c28a6236c56f4b254c634e53235958f7f50cc".parse::<H256>()?;
        println!("tx_hash: {:?}", tx_hash);
        let tx_parameters = provider.get_transaction(tx_hash).await?.unwrap();
        println!("tx_parameters: {:?}", tx_parameters);
        let block_transactions = current_block_parameters.clone().unwrap().transactions;
        println!("Got block_transactions: {:?}", block_transactions);
        let ens_balance = provider.get_balance("car.eth", None).await?;
        println!("ENS address balance: {}", ens_balance);
    }
    if chainid == U256::from(8081) {//Shardeum Liberty 2.X
        let tx_hash = "0xc0478ea8a26fa562ea8ff6640f2090ac8fa075704bb5f973ab0448a1f2ac22c3".parse::<H256>()?;
        println!("tx_hash: {:?}", tx_hash);
        let tx_parameters = provider.get_transaction(tx_hash).await?.unwrap();
        println!("tx_parameters: {:?}", tx_parameters);
        //Shardeum will not show transactions in bundles (blocks). 
        //Use the Shardeum Explorer JSON URL view with filters to get transactions from cycle ranges: 
        //https://docs.shardeum.org/smartContracts/events/pollEvents#reading-events-with-shardeum-cycles
    }

    Ok(())

}
```

##### What other resources can you share regarding this issue?

Goerli transaction:

https://goerli.etherscan.io/tx/0x7bd590a4c9100402fb105f7de66c28a6236c56f4b254c634e53235958f7f50cc

Liberty 2.1 transaction:

https://explorer-liberty20.shardeum.org/tx/0xc0478ea8a26fa562ea8ff6640f2090ac8fa075704bb5f973ab0448a1f2ac22c3

**Comment by MarcusWentz** [comment]
The issue is present in Javascript as well with ethers.js with the following error:

```
chainIdConnected: 8081
/home/marcuswentz/node_modules/@ethersproject/logger/lib/index.js:238
        var error = new Error(message);
                    ^

Error: invalid BigNumber string (argument="value", value="8ac7230489e80000", code=INVALID_ARGUMENT, version=bignumber/5.7.0)
    at Logger.makeError (/home/marcuswentz/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/home/marcuswentz/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at Logger.throwArgumentError (/home/marcuswentz/node_modules/@ethersproject/logger/lib/index.js:250:21)
    at Function.BigNumber.from (/home/marcuswentz/node_modules/@ethersproject/bignumber/lib/bignumber.js:199:27)
    at Formatter.bigNumber (/home/marcuswentz/node_modules/@ethersproject/providers/lib/formatter.js:151:38)
    at Function.Formatter.check (/home/marcuswentz/node_modules/@ethersproject/providers/lib/formatter.js:380:40)
    at Formatter.transactionResponse (/home/marcuswentz/node_modules/@ethersproject/providers/lib/formatter.js:290:32)
    at JsonRpcProvider.<anonymous> (/home/marcuswentz/node_modules/@ethersproject/providers/lib/base-provider.js:2120:65)
    at step (/home/marcuswentz/node_modules/@ethersproject/providers/lib/base-provider.js:48:23)
    at Object.next (/home/marcuswentz/node_modules/@ethersproject/providers/lib/base-provider.js:29:53) {
  reason: 'invalid BigNumber string',
  code: 'INVALID_ARGUMENT',
  argument: 'value',
  value: '8ac7230489e80000',
  checkKey: 'value',
  checkValue: '8ac7230489e80000'
}
```

Test script:

```javascript
const ethers = require("ethers")

// const rpcURL = process.env.goerliHTTPS_InfuraAPIKey //Goerli
const rpcURL = "https://liberty20.shardeum.org/" //Shardeum Liberty 2.1

const provider = new ethers.providers.JsonRpcProvider(rpcURL)

createAndSendTx();

async function createAndSendTx() {

  const connectedNetworkObject = await provider.getNetwork();
  const chainIdConnected = connectedNetworkObject.chainId;
  console.log("chainIdConnected: "+ chainIdConnected)

  if(chainIdConnected == 5) { //Goerli
    tx_info = await provider.getTransaction("0x7bd590a4c9100402fb105f7de66c28a6236c56f4b254c634e53235958f7f50cc")
    console.log(tx_info)
  }
  if(chainIdConnected == 8081) { //Shardeum Liberty 2.1
    tx_info = await provider.getTransaction("0xc0478ea8a26fa562ea8ff6640f2090ac8fa075704bb5f973ab0448a1f2ac22c3")
    console.log(tx_info)
  }

}

```

**Comment by MarcusWentz** [comment]
Here is another way to get the transaction by hash using the Shardeum Explorer JSON URL with a ```txHash``` filter:

https://explorer-liberty10.shardeum.org/api/transaction?txHash=0xa44a5e5d20122afcab95916073e2e682865da7d05bce0c417f2cdad6d9085d11

**Comment by MarcusWentz** [comment]
It's possible this issue is occurring based on the transaction's MSG.VALUE parameter (value) is a hex value instead of a decimal value based on the Javascript log.

**Comment by MarcusWentz** [comment]
Confirmed bug root cause https://github.com/Shardeum/shardeum-bug-reporting/issues/24#issuecomment-1398904377 with:

```javascript
const ethers = require("ethers")

// const rpcURL = process.env.goerliHTTPS_InfuraAPIKey //Goerli
const rpcURL = "https://liberty20.shardeum.org/" //Shardeum Liberty 2.1

const provider = new ethers.providers.JsonRpcProvider(rpcURL)

createAndSendTx();

async function createAndSendTx() {

  const connectedNetworkObject = await provider.getNetwork();
  const chainIdConnected = connectedNetworkObject.chainId;
  console.log("chainIdConnected: "+ chainIdConnected)

  if(chainIdConnected == 5) { //Goerli
    tx_info = await provider.getTransaction("0x7bd590a4c9100402fb105f7de66c28a6236c56f4b254c634e53235958f7f50cc")
    console.log(tx_info)
  }
  if(chainIdConnected == 8081) { //Shardeum Liberty 2.1
    // Success 
    tx_info_decimal_pass = await provider.getTransaction("0x28fc8a687a31ff3a07086b7fc4a7986c758aaaba186387e1502ee1ced1317721") // 9 WEI, works.
    // https://explorer-liberty20.shardeum.org/api/transaction?txHash=0x28fc8a687a31ff3a07086b7fc4a7986c758aaaba186387e1502ee1ced1317721

    console.log(tx_info_decimal_pass)

    // Fail
    tx_info_hexadecimal_fail = await provider.getTransaction("0x08a0e3064c4c195aad793235f23a6dc2959f66f2adbef0b1ba611df4d945069b") // 10 WEI (hexadecimal: "a") works.
    // https://explorer-liberty20.shardeum.org/api/transaction?txHash=0x08a0e3064c4c195aad793235f23a6dc2959f66f2adbef0b1ba611df4d945069b
  
    console.log(tx_info_hexadecimal_fail)
  }

}
```

**Comment by MarcusWentz** [comment]
In Javascript, the type for value should be a BigInt hexadecimal string instead of a raw hexadecimal string.

For example: https://goerli.etherscan.io/tx/0x7bd590a4c9100402fb105f7de66c28a6236c56f4b254c634e53235958f7f50cc
with msg.value = 0.2 ether returns:

```javascript
value: BigNumber { _hex: '0x0f3dbb76162000', _isBigNumber: true }
```
