### ISSUE TITLE
[Duplicate] Validator CLI ```operator-cli status``` error ```AxiosError: Request failed with status code 500 ERR_BAD_RESPONSE```

### ISSUE THREAD

**Issue by mateuszmr** [Shardeum/shardeum-bug-reporting#246]
My validator is still in standby mode, almost two weeks now. I began to wonder why. I have the same error which is described in issue [#225](https://github.com/Shardeum/shardeum-bug-reporting/issues/225)  Additionally, I have an AxiosError appearing after typing the `operator-cli status` command

From the GUI side, everything looks good

```
AxiosError: Request failed with status code 500
    at settle (/home/node/app/cli/node_modules/axios/dist/node/axios.cjs:1859:12)
    at IncomingMessage.handleStreamEnd (/home/node/app/cli/node_modules/axios/dist/node/axios.cjs:2723:11)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ERR_BAD_RESPONSE',
```

![image](https://user-images.githubusercontent.com/45229710/227724510-0ab0491e-1e82-4d7b-99b3-ffd32457a551.png)

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/80
