### ISSUE TITLE
[Duplicate] Validators Not Active in more than one and a half month

### ISSUE THREAD

**Issue by Sylwester79** [Shardeum/shardeum-bug-reporting#315]
new version 1.1.6 clean install
VPS hosting

node status not active for many days

bugs found:

"p2p log"
[WARN] p2p - Self: Error while joining network:
[WARN] p2p - Self: Error: Node not ready to join
[WARN] p2p - Self: Error: Node not ready to join

[WARN] p2p - Self: Error while joining network:
[2023-04-10T09:18:08.509] [WARN] p2p - Self: TimeoutError: Timeout awaiting 'request' for 1000ms
[2023-04-10T09:18:08.509] [WARN] p2p - Self: TimeoutError: Timeout awaiting 'request' for 1000ms
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/got/source/request-as-event-emitter.js:176:14)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:402:35)
    at ClientRequest.origin.emit (/usr/src/app/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at Immediate.timeoutHandler (/usr/src/app/node_modules/got/source/utils/timed-out.js:63:11)
    at processImmediate (node:internal/timers:466:21)

i have such an entry i log file ,despite the execution of the commandexport APP_IP="EXTERNAL_IP" , .env file is ok  

![ip](https://user-images.githubusercontent.com/128922366/230885551-f527aba6-5d2f-46b5-9556-cf783a828192.jpg)

exit-summary.json file 

"externalIp": "0.0.0.0",
    "externalPort": 9001,
    "internalIp": "0.0.0.0",
    "internalPort": 10001,
    "status": null

logs in the attachment

![node](https://user-images.githubusercontent.com/128922366/230849356-13b772e5-dd96-4659-a507-3784ab90a096.jpg)
[logs.zip](https://github.com/Shardeum/shardeum-bug-reporting/files/11188537/logs.zip)

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/282
