### ISSUE TITLE
Validator CLI `operator-cli stake` Error `could not detect network`

### ISSUE THREAD

**Issue by camzilla1050** [Shardeum/shardeum-bug-reporting#364]
##### What is the issue?

Using command **operator-cli stake 10** returns code "network error"    

```
node@2e07fa90eb67:~/app$ operator-cli stake 10
Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)
    at Logger.makeError (/home/node/app/cli/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/home/node/app/cli/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at JsonRpcProvider.<anonymous> (/home/node/app/cli/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:609:54)
    at step (/home/node/app/cli/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/home/node/app/cli/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/home/node/app/cli/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'could not detect network',
  code: 'NETWORK_ERROR',
  event: 'noNetwork'
}

```
Also retruns

```
node@2e07fa90eb67:~/app$ operator-cli stake 10
{
  isInternalTx: true,
  internalTXType: 6,
  nominator: '0xa49371b6a385e620e24b13399ef170b990cb2fa4',
  timestamp: 1682802607220,
  nominee: '913d11db894d48241d4bfacc96b6cb0b3127d3316b220216cd8d27b87437c15a',
  stake: '10000000000000000000'
}
Error: bad response (status=500, headers={"date":"Sat, 29 Apr 2023 21:10:12 GMT","content-type":"text/html"
.... requestBody="{.... requestMethod="POST", url="https://sphinx.shardeum.org", code=SERVER_ERROR, version=web/5.7.1)
    at Logger.makeError (/home/node/app/cli/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/home/node/app/cli/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at /home/node/app/cli/node_modules/@ethersproject/web/lib/index.js:275:36
    at step (/home/node/app/cli/node_modules/@ethersproject/web/lib/index.js:33:23)
    at Object.next (/home/node/app/cli/node_modules/@ethersproject/web/lib/index.js:14:53)
    at fulfilled (/home/node/app/cli/node_modules/@ethersproject/web/lib/index.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'bad response',
  code: 'SERVER_ERROR',
  status: 500,
  headers: {
    date: 'Sat, 29 Apr 2023 21:10:12 GMT',
    'content-type': 'text/html',
    'transfer-encoding': 'chunked',
    connection: 'close',
    'cf-cache-status': 'DYNAMIC',
   ....
  requestBody: '{"method":"eth_getBlockByNumber","params":["latest",false],"id":49,"jsonrpc":"2.0"}',
  requestMethod: 'POST',
  url: 'https://sphinx.shardeum.org'
}

```

**Comment by skundu42** [comment]
This should be resolved now with newer validator updates.
