### ISSUE TITLE
[Duplicate] Validator Version 1.2.0 Cannot Start Validator and GUI Becomes Blank After Trying To Start Validator

### ISSUE THREAD

**Issue by senkiss** [Shardeum/shardeum-bug-reporting#369]
when i run operator-cli status,got this error!
/home/node/app/cli/build/src/utils/fetch-network-data.js:139
    if (nodeInfo === null || nodeInfo.nodeInfo === null) {
                                      ^

TypeError: Cannot read properties of undefined (reading 'nodeInfo')
    at fetchNodeInfo (/home/node/app/cli/build/src/utils/fetch-network-data.js:139:39)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:526:9)
    at processTimers (node:internal/timers:500:7)
    at async /home/node/app/cli/build/src/node-commands.js:205:34

**Comment by MarcusWentz** [comment]
Duplicate issue.

Share this info here:

https://github.com/Shardeum/shardeum-bug-reporting/issues/367
