### ISSUE TITLE
Validator 1.2.2, Exit with warning, Process exited with SIGINT, ECONNREFUSED

### ISSUE THREAD

**Issue by Shekelme** [Shardeum/shardeum-bug-reporting#384]
##### What is the issue?

The node cannot start after upgrade to 1.2.x. It says:
![image](https://github.com/Shardeum/shardeum-bug-reporting/assets/26449500/807fb82b-93ca-4d72-aa40-2e67f776aece)

    
#### What impact does the issue have?

I simply cannot stake validate.

##### How to reproduce the issue? 

Upgrade Shardeum to 1.2.x, set "Internal IP" to "auto" and enjoy the problem.

##### What other resources can you share regarding this issue?

```
node@6f2e44e1788b:~/app/cli/build/logs$ cat exit-summary.json
{
  "status": "Exit with warning",
  "message": "Process exited with SIGINT",
  "exitTime": 1684036772506,
  "totalActiveTime": 0,
  "nodeInfo": {
    "publicKey": "486e5d5ca78504e402feaab87ae7fd43b14951fb0dbe010267d964733a3dfae8",
    "curvePublicKey": "2c56b99804ff8b49c01edb504e436986d0ccce9efe59f94de43fbd19172af955",
    "externalIp": "212.15.58.91",
    "externalPort": 9001,
    "internalIp": "212.15.58.91",
    "internalPort": 10001,
    "status": null
  },
  "activeNodes": 0

```

And also

```
node@6f2e44e1788b:~/app$ operator-cli status
AxiosError: connect ECONNREFUSED 212.15.58.91:9001
    at Function.AxiosError.from (/home/node/app/cli/node_modules/axios/dist/node/axios.cjs:789:14)
    at RedirectableRequest.handleRequestError (/home/node/app/cli/node_modules/axios/dist/node/axios.cjs:2744:25)
    at RedirectableRequest.emit (node:events:402:35)
    at ClientRequest.eventHandlers.<computed> (/home/node/app/cli/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:390:28)
    at Socket.socketErrorListener (node:_http_client:447:9)
    at Socket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  port: 9001,
  address: '212.15.58.91',
  syscall: 'connect',
  code: 'ECONNREFUSED',
  errno: -111,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 2000,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: null },
    validateStatus: [Function: validateStatus],
    headers: AxiosHeaders {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/1.2.2',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'get',
    url: 'http://212.15.58.91:9001/nodeinfo',
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Array]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'http:',
      path: '/nodeinfo',
      method: 'GET',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: '212.15.58.91',
      port: '9001',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/nodeinfo'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'GET /nodeinfo HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/1.2.2\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: 212.15.58.91:9001\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/nodeinfo',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '212.15.58.91',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'http://212.15.58.91:9001/nodeinfo',
    _timeout: null,
    [Symbol(kCapture)]: false
  },
  cause: Error: connect ECONNREFUSED 212.15.58.91:9001
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '212.15.58.91',
    port: 9001
  }
}
/home/node/app/cli/build/src/utils/fetch-network-data.js:141
        throw new Error('Node not active in the network. Unable to fetch node-info');
              ^

Error: Node not active in the network. Unable to fetch node-info
    at fetchNodeInfo (/home/node/app/cli/build/src/utils/fetch-network-data.js:141:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /home/node/app/cli/build/src/node-commands.js:205:34
```

**Comment by MarcusWentz** [comment]
Related to:

https://github.com/Shardeum/shardeum-bug-reporting/issues/367

Did you configure your router to have TCP p2p ports 9001 and 10001 open?
Example:
https://www.att.com/support/article/u-verse-high-speed-internet/KM1010280/
Reference:
https://docs.shardeum.org/node/run/validator#step-2-download-and-install-validator

**Comment by Shekelme** [comment]
Yes, and these ports are open:
![image](https://github.com/Shardeum/shardeum-bug-reporting/assets/26449500/6c75a155-fc72-4aa1-87c4-4cb6ab72b30d)

**Comment by Shekelme** [comment]
Browser console's output.
[192.168.0.20-1684045704378.log](https://github.com/Shardeum/shardeum-bug-reporting/files/11471283/192.168.0.20-1684045704378.log)

**Comment by Shekelme** [comment]
Finally I made it work.
My workaround was to create 2 additional NAT rules on my Mikrotik. They should look something like this:
`ip firewall nat add chain=dstnat dst-address=212.15.58.91 protocol=tcp dst-port=9001 in-interface=bridge2 action=dst-nat to-addresses=192.168.0.20 to-ports=9001`

And
`ip firewall nat add chain=srcnat src-address=192.168.0.0/24 dst-address=192.168.0.20 protocol=tcp dst-port=9001 out-interface=bridge2 action=masquerade`
 
The problem was that Shardeum validator is trying to get some data using public IP `212.15.58.91` which can be inaccessible locally by default. At least as far as I understood the essence of the problem. ))
