### ISSUE TITLE
thread 'tokio-runtime-worker' panicked at 'Cannot start a runtime from within a runtime.

### ISSUE THREAD

**Issue by likemusic** [Shardeum/shardeum-bug-reporting#408]
##### What is the issue?

Node down and not autorestart. Even though in Settings "Enable Auto-restart" is enabled.
    
#### What impact does the issue have?

Validator node stoped.

##### How to reproduce the issue? 

Just start node.

##### What other resources can you share regarding this issue?

```
CLI/GUI Running Version: 1.2.1 / 1.2.0
CLI/GUI Latest Version: 1.2.1 / 1.2.0
Validator Running Version: 1.4.0
Active Network Version: 1.4.0
Validator Minimum Version: 1.4.0
```

From `/home/node/.pm2/logs/validator-error.log`.
```
thread 'tokio-runtime-worker' panicked at 'Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.$
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.$
stack backtrace:
   0:     0x7f089cc0539a - std::backtrace_rs::backtrace::libunwind::trace::h9a6b80bbf328ba5d
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f089cc0539a - std::backtrace_rs::backtrace::trace_unsynchronized::hd162ec543a11886b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f089cc0539a - std::sys_common::backtrace::_print_fmt::h78a5099be12f51a6
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f089cc0539a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha1c5390454d74f71
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f089cc23f6f - core::fmt::write::h9ffde816c577717b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/fmt/mod.rs:1254:17
   5:     0x7f089cc02525 - std::io::Write::write_fmt::h88186074961638e4
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/io/mod.rs:1698:15
   6:     0x7f089cc05165 - std::sys_common::backtrace::_print::h184198273ed08d59
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f089cc05165 - std::sys_common::backtrace::print::h1b4d8e7add699453
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f089cc0680e - std::panicking::default_hook::{{closure}}::h393bcea75423915a
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:269:22
   9:     0x7f089cc065b5 - std::panicking::default_hook::h48c64f31d8b3fd03
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:288:9
  10:     0x7f089cc06d6e - std::panicking::rust_panic_with_hook::hafdc493a79370062
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:691:13
  11:     0x7f089cc06c22 - std::panicking::begin_panic_handler::{{closure}}::h0a64bc82e36bedc7
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:580:13
  12:     0x7f089cc05806 - std::sys_common::backtrace::__rust_end_short_backtrace::hc203444fb7416a16
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18
  13:     0x7f089cc069c2 - rust_begin_unwind
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
  14:     0x7f089ca392d3 - core::panicking::panic_fmt::h0f6ef0178afce4f2
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
  15:     0x7f089cb84c91 - tokio::runtime::context::enter_runtime::h949a9b4390306e6c
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/context.rs:183:9
  16:     0x7f089cac18fc - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::hddd5603860ef8ac5
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/mod.rs:65:25
  17:     0x7f089ca61053 - tokio::runtime::runtime::Runtime::block_on::h4a2156b2f02fe662
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/runtime.rs:304:45
  18:     0x7f089cac09c9 - <shardus_net::shardus_net_sender::Connection as core::ops::drop::Drop>::drop::hb46b31a71d661475
                               at /usr/src/app/node_modules/@shardus/net/src/shardus_net_sender.rs:142:13
```

First link by googling show https://github.com/tokio-rs/tokio/discussions/3857 which may be related.

**Comment by skundu42** [comment]
this should be resolved with 1.5.1 update
