### ISSUE TITLE
Connect to Validator Dashboard - invalid password

### ISSUE THREAD

**Issue by okara533** [Shardeum/shardeum-bug-reporting#413]
When I try to login validator dashboard from localhost, I typed password. It returns Invalid Password.
I changed pass word with:
operator-cli gui set password 1234 //example password
when I login from browser It returns Invalid Password
![image](https://github.com/Shardeum/shardeum-bug-reporting/assets/31192188/7393d613-f6e4-4d24-94ae-bfc4685379ca)

when I try on command line:
operator-cli gui login 1234
It returns following error:
/home/node/app/cli/build/src/gui-commands.js:128
        if (!(0, crypto_1.timingSafeEqual)(Buffer.from(password), Buffer.from(config.gui.pass))) {
                                          ^

RangeError: Input buffers must have the same byte length
    at Command.<anonymous> (/home/node/app/cli/build/src/gui-commands.js:128:43)
    at Command.listener [as _actionHandler] (/home/node/app/cli/node_modules/commander/lib/command.js:482:17)
    at /home/node/app/cli/node_modules/commander/lib/command.js:1264:65
    at Command._chainOrCall (/home/node/app/cli/node_modules/commander/lib/command.js:1158:12)
    at Command._parseCommand (/home/node/app/cli/node_modules/commander/lib/command.js:1264:27)
    at /home/node/app/cli/node_modules/commander/lib/command.js:1062:27
    at Command._chainOrCall (/home/node/app/cli/node_modules/commander/lib/command.js:1158:12)
    at Command._dispatchSubcommand (/home/node/app/cli/node_modules/commander/lib/command.js:1058:23)
    at Command._parseCommand (/home/node/app/cli/node_modules/commander/lib/command.js:1229:19)
    at /home/node/app/cli/node_modules/commander/lib/command.js:1062:27 {
  code: 'ERR_CRYPTO_TIMING_SAFE_EQUAL_LENGTH'
}

How can I set password or how can I login with my password

**Comment by skundu42** [comment]
@okara533 Can you check again by installing the latest validator update?
