### ISSUE TITLE
Validator Stopped After Running For Several Days With Status ```AxiosError: connect ECONNREFUSED```

### ISSUE THREAD

**Issue by coldsjf** [Shardeum/shardeum-bug-reporting#49]
##### What is the issue?

The validator crashed randomly. 
    
#### What impact does the issue have?

Validator stopped working, but the web service is fine, but no data is showing.

##### How to reproduce the issue? 

The validator was running 2-3 days with no problem, then crashed randomly. 

##### What other resources can you share regarding this issue?

Crash log:

```shell
`AxiosError: connect ECONNREFUSED 169.254.77.5:4000
    at Function.AxiosError.from (/home/node/app/cli/node_modules/axios/dist/node/axios.cjs:789:14)
    at RedirectableRequest.handleRequestError (/home/node/app/cli/node_modules/axios/dist/node/axios.cjs:2744:25)
    at RedirectableRequest.emit (node:events:390:28)
    at ClientRequest.eventHandlers.<computed> (/home/node/app/cli/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:390:28)
    at Socket.socketErrorListener (node:_http_client:447:9)
    at Socket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  port: 4000,
  address: '169.254.77.5',
  syscall: 'connect',
  code: 'ECONNREFUSED',
  errno: -111,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: null },
    validateStatus: [Function: validateStatus],
    headers: AxiosHeaders {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/1.2.2',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'get',
    url: 'http://archiver-sphinx.shardeum.org:4000/nodelist',
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'http:',
      path: '/nodelist',
      method: 'GET',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: 'archiver-sphinx.shardeum.org',
      port: '4000',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/nodelist'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'GET /nodelist HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/1.2.2\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: archiver-sphinx.shardeum.org:4000\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/nodelist',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'archiver-sphinx.shardeum.org',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'http://archiver-sphinx.shardeum.org:4000/nodelist',
    [Symbol(kCapture)]: false
  },
  cause: Error: connect ECONNREFUSED 169.254.77.5:4000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '169.254.77.5',
    port: 4000
  }
}
/home/node/app/cli/build/src/utils/fetch-network-data.js:37
    if (nodeList === null || nodeList.nodeList === null) {
                                      ^

TypeError: Cannot read properties of undefined (reading 'nodeList')
    at getActiveNode (/home/node/app/cli/build/src/utils/fetch-network-data.js:37:39)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async fetchDataFromNetwork (/home/node/app/cli/build/src/utils/fetch-network-data.js:14:9)
    at async fetchStakeParameters (/home/node/app/cli/build/src/utils/fetch-network-data.js:124:25)
    at async /home/node/app/cli/build/src/node-commands.js:122:39`
```

**Comment by MarcusWentz** [comment]
Is this from a local computer or remote server?

**Comment by coldsjf** [comment]
> 

this was from Ubuntu server. And I will test the betanet1.1 soon.

**Comment by MarcusWentz** [comment]
Please update your validator to version 1.1.1.

Here's what you need to do:

1. Stop and unstake your validator.
2. If you're within the Validator CLI:

```shell
exit
```

then: 

```shell
cd ..
```

3. Enter:

```shell
curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh
```

4. Start the validator.
5. Stake 10 SHM.

**Comment by MarcusWentz** [comment]
Closing issue for now.

We can reopen the issue if it comes back or is still present.
