### ISSUE TITLE
node gui show error!

### ISSUE THREAD

**Issue by pupudaye** [Shardeum/shardeum-bug-reporting#527]
![image](https://github.com/shardeum/shardeum-bug-reporting/assets/31983567/a1f5a281-d833-461d-9299-a9b76a1d4325)

##### What is the issue?

:red_circle:  Describe the error in simple terms. :red_circle: 
    
#### What impact does the issue have?

:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    -where the error is seen
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle:

**Comment by green-creeper** [comment]
Have the same issue. This is what I see in log:
```
/home/node/app/cli/build/src/utils/fetch-network-data.js:109
        throw new Error(`Unable to fetch data from network (out of retries: ${reason}).`);
              ^

Error: Unable to fetch data from network (out of retries: unknown reason).
    at fetchDataFromNetwork (/home/node/app/cli/build/src/utils/fetch-network-data.js:109:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchInitialParameters (/home/node/app/cli/build/src/utils/fetch-network-data.js:151:27)
    at async getAccountInfoParams (/home/node/app/cli/build/src/utils/fetch-network-data.js:257:54)
    at async Promise.all (index 4)
    at async /home/node/app/cli/build/src/node-commands.js:222:153
```
