### ISSUE TITLE
Sorry, something went wrong. Please report this issue to our support team so we can investigate and resolve the problem. 

### ISSUE THREAD

**Issue by shilohma** [Shardeum/shardeum-bug-reporting#617]
##### What is the issue?

:red_circle:  Describe the error in simple terms. :red_circle: 
    
#### What impact does the issue have?
Sorry, something went wrong. Please report this issue to our support team so we can investigate and resolve the problem. 
Error reporting when entering on the web side.

operator-cli status
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFileSync (node:fs:2239:5)
    at getNewActiveNode (/home/node/app/cli/build/src/utils/fetch-network-data.js:138:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchDataFromNetwork (/home/node/app/cli/build/src/utils/fetch-network-data.js:67:9)
    at async fetchStakeParameters (/home/node/app/cli/build/src/utils/fetch-network-data.js:296:25)
    at async Promise.all (index 0)
    at async /home/node/app/cli/build/src/node-commands.js:222:153 {
  code: 'ERR_INVALID_ARG_TYPE'
}

:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    -where the error is seen
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle:

**Comment by CentLeeMan** [comment]
Web admin error: Sorry, something went wrong. Please report this issue to our support team so we can investigate and resolve the problem. [Report Issue]
In node server command: PM2 list
Node -fork - online

**Comment by shilohma** [comment]
>>>> In-memory PM2 is out-of-date, do:
>>>> $ pm2 update
In memory PM2 version: 5.3.0
Local PM2 version: 5.3.1

┌────┬─────────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name            │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├────┼─────────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0  │ operator-gui    │ default     │ N/A     │ fork    │ 624      │ 2h     │ 0    │ online    │ 0%       │ 71.4mb   │ node     │ disabled │
└────┴─────────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘

**Comment by shilohma** [comment]
![image](https://github.com/shardeum/shardeum-bug-reporting/assets/109585356/ffdf31b6-027e-4671-873f-0e9cc4081b9f)
