### ISSUE TITLE
The node cannot run and reinstalling cannot solve the problem.

### ISSUE THREAD

**Issue by oscarsum** [Shardeum/shardeum-bug-reporting#748]
##### Any questions?

:red_circle: Briefly describe the error. : During my daily check, I found that the node containers of 9 servers were shut down. This is a normal situation for Shardeum. So I restarted the container, but it didn't work this time. I didn't record the error message, but I remember it was related to port 8080. These 9 servers have been running sharedeum nodes for 2-3 months. This has never happened before, but this problem does not occur on other servers.
    
#### What is the impact of this issue?

:red_circle: Describes whether the error is a visual warning, or whether it breaks functionality causing the system to fail. :Red circle: So, I could only delete and reinstall the node. During the installation, I deliberately found the unoccupied 8088 port to replace the 8080 port. Even though I was sure that there would be no problem if I used the 8080 port, because in I had been using port 8080 for a long time before this, and I had to reinstall it several times.

However, this time it still cannot be solved, and an error is still reported: Recreating 8169cda4c98c_shardeum-dashboard ... error
ERROR: for 8169cda4c98c_shardeum-dashboard No such image: sha256:ef40f73b041a621e3d03559ddfcb14f067487ada63d02212184606678403838e

ERROR: for shardeum-dashboard No such image: sha256:ef40f73b041a621e3d03559ddfcb14f067487ada63d02212184606678403838e
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Recreating 8169cda4c98c_shardeum-dashboard ...

ERROR: for 8169cda4c98c_shared-dashboard 'ContainerConfig'

ERROR: for share-dashboard 'ContainerConfig'
Traceback (most recent call last):
   File "docker/api/client.py", line 268, in _raise_for_status
   File "requests/models.py", line 941, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.45/images/sha256:ef40f73b041a621e3d03559ddfcb14f067487ada63d02212184606678403838e/json

##### How to reproduce the problem?

:Red circle:
Explain in as much detail as possible to help reproduce the error: I used the following code after a failed reinstall and then reinstalled again:
cd ~/.sharedeum
./cleanup.sh
cd ~/
rm -rf .sharedeum
rm installer.sh
curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh
 
````
:Red circle: Then, the problem is still the same: Trying again with sudo...
Recreating 8169cda4c98c_shardeum-dashboard... error
ERROR: for 8169cda4c98c_shardeum-dashboard No such image: sha256:ef40f73b041a621e3d03559ddfcb14f067487ada63d02212184606678403838e

ERROR: for shardeum-dashboard No such image: sha256:ef40f73b041a621e3d03559ddfcb14f067487ada63d02212184606678403838e
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Finally, I tried to restart the container according to the discord administrator's prompts, but the following error still occurred: Error response from daemon: driver failed programming external connectivity on endpoint 7e9fc5394a97_shardeum-dashboard (993ad8ce51f7e7fe858bdbf126b12edb4134548047e8cba6fd40f0d4c989bd6e): Error starting user land proxy: listen tcp4 0.0.0.0: 8080: bind: address already in use
Error: failed to start containers: 7e9fc5394a97

**Comment by stewfarq** [comment]
I get this same error too.  When I recreate the image I get...

Continue with the new image? [yN]y
Recreating 68527b7669c3_shardeum-dashboard ... 

ERROR: for 68527b7669c3_shardeum-dashboard  'ContainerConfig'

ERROR: for shardeum-dashboard  'ContainerConfig'
Traceback (most recent call last):
  File "docker/api/client.py", line 268, in _raise_for_status
  File "requests/models.py", line 941, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.46/images/sha256:8692bd95519ce3fefba706d35599a955fd1384a5056fae0325be6cac0343d6f1/json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "compose/cli/main.py", line 1186, in up
  File "compose/cli/main.py", line 1182, in up
  File "compose/project.py", line 702, in up
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/project.py", line 688, in do
  File "compose/service.py", line 581, in execute_convergence_plan
  File "compose/service.py", line 503, in _execute_convergence_recreate
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/service.py", line 496, in recreate
  File "compose/service.py", line 615, in recreate_container
  File "compose/service.py", line 334, in create_container
  File "compose/service.py", line 922, in _get_container_create_options
  File "compose/service.py", line 962, in _build_container_volume_options
  File "compose/service.py", line 1549, in merge_volume_bindings
  File "compose/service.py", line 1579, in get_container_data_volumes
  File "compose/container.py", line 61, in image_config
  File "docker/utils/decorators.py", line 19, in wrapped
  File "docker/api/image.py", line 254, in inspect_image
  File "docker/api/client.py", line 274, in _result
  File "docker/api/client.py", line 270, in _raise_for_status
  File "docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.46/images/sha256:8692bd95519ce3fefba706d35599a955fd1384a5056fae0325be6cac0343d6f1/json: Not Found ("No such image: sha256:8692bd95519ce3fefba706d35599a955fd1384a5056fae0325be6cac0343d6f1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 203, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 1197, in up
  File "compose/cli/main.py", line 1182, in up
  File "compose/project.py", line 702, in up
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/project.py", line 688, in do
  File "compose/service.py", line 581, in execute_convergence_plan
  File "compose/service.py", line 503, in _execute_convergence_recreate
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/service.py", line 496, in recreate
  File "compose/service.py", line 615, in recreate_container
  File "compose/service.py", line 334, in create_container
  File "compose/service.py", line 922, in _get_container_create_options
  File "compose/service.py", line 962, in _build_container_volume_options
  File "compose/service.py", line 1549, in merge_volume_bindings
  File "compose/service.py", line 1579, in get_container_data_volumes
KeyError: 'ContainerConfig'
[12896] Failed to execute script docker-compose

----------------

docker version
Client: Docker Engine - Community
 Version:           27.1.2
 API version:       1.46
 Go version:        go1.21.13
 Git commit:        d01f264
 Built:             Mon Aug 12 11:51:03 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.1.2
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.13
  Git commit:       f9522e5
  Built:            Mon Aug 12 11:51:03 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.20
  GitCommit:        8fc6bcff51318944179630522a095cc9dbf9f353
 runc:
  Version:          1.1.13
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
