### ISSUE TITLE
Cannot get list of nodes

### ISSUE THREAD

**Issue by cvlescu** [Shardeum/shardeum-bug-reporting#756]
##### What is the issue?

:red_circle: Cannot receive list of nodes :red_circle: 
    
#### What impact does the issue have?

:red_circle: Validator cannot run properly. Incentives are not received :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Validator received incentives for a few days and then stopped receiving them. 
Nothing unusual in GUI, but running operator-cli status shows that it cannot get list of nodes anymore:

node@f0de3d21a022:~/app$ operator-cli status
AxiosError: connect ECONNREFUSED 172.233.176.64:4000
    at AxiosError.from (/home/node/app/cli/node_modules/axios/dist/node/axios.cjs:836:14)
    at RedirectableRequest.handleRequestError (/home/node/app/cli/node_modules/axios/dist/node/axios.cjs:3010:25)
    at RedirectableRequest.emit (node:events:525:35)
    at eventHandlers.<computed> (/home/node/app/cli/node_modules/follow-redirects/index.js:37:24)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  port: 4000,
  address: '172.233.176.64',
  syscall: 'connect',
  code: 'ECONNREFUSED',
  errno: -111,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 2000,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: AxiosHeaders {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/1.4.0',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'get',
    url: 'http://172.233.176.64:4000/nodelist',
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Array]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'http:',
      path: '/nodelist',
      method: 'GET',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      family: undefined,
      lookup: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: '172.233.176.64',
      port: '4000',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/nodelist'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'GET /nodelist HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/1.4.0\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: 172.233.176.64:4000\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/nodelist',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '172.233.176.64',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'http://172.233.176.64:4000/nodelist',
    _timeout: null,
    [Symbol(kCapture)]: false
  },
  cause: Error: connect ECONNREFUSED 172.233.176.64:4000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '172.233.176.64',
    port: 4000
  }
}
state: standby
totalTimeRunning: 96786.109
totalTimeValidating: '00:00:00'
lastActive: ''
lastRotationIndex: ''
stakeRequirement: '10.0'
nominatorAddress: '0xc4a444a8d680406cd361d394c6cb89e425432709'
nomineeAddress: 7bd401095fd6273a7c386c34a40e8410d6b8e4fe01fe5d4a3dca33cd02f1a967
performance:
  memPercentage: 2.455923751333927
  diskPercentage: 1.6747051832142197
  cpuPercentage: 0.7499999999999951
currentRewards: '96.549999999999999999'
lockedStake: '10.0'
totalPenalty: '0.0'
autorestart: true
nodeInfo:
  publicKey: 7bd401095fd6273a7c386c34a40e8410d6b8e4fe01fe5d4a3dca33cd02f1a967
  curvePublicKey: 73386485d49034bc2044e5efa6ee31b798df628231ffeaacfcd2fbe721bb8d22
  externalIp: 178.63.16.58
  externalPort: 9001
  internalIp: 178.63.16.58
  internalPort: 10001
  status: standby
  appData:
    shardeumVersion: 1.10.3
    minVersion: 1.10.3
    activeVersion: 1.10.3
    latestVersion: 1.10.3
    operatorCLIVersion: 1.2.1
    operatorGUIVersion: 1.2.0

:red_circle: 

##### What other resources can you share regarding this issue?
I checked connection to the IP, ping worked:
 ping  172.233.176.64
PING 172.233.176.64 (172.233.176.64) 56(84) bytes of data.
64 bytes from 172.233.176.64: icmp_seq=1 ttl=53 time=117 ms
64 bytes from 172.233.176.64: icmp_seq=2 ttl=53 time=117 ms
^C
--- 172.233.176.64 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms

First instructions from discord were:
Try resetting your wallet and try again.
You can also switch to this RPC: https://rpc2-sphinx.shardeum.org/

Performed both, the issue persisted

As instructed on discord, cleaned everything and performed a new install:
cd ~/.shardeum
./cleanup.sh
cd ~/
rm -rf .shardeum
rm installer.sh
curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh

The ECONNREFUSED issue still persists.

:red_circle: Photos and links related to the error. :red_circle: 
GUI looked ok, error was not highlighted there.

**Comment by michal-ambroziak** [comment]
I'm having the same problem with version 1.10.3. The node is in Standby mode but stops after some time.
URL http://172.233.176.64:4000/nodelist doesn't return anything.
