### ISSUE TITLE
Sorry, something went wrong. Please report this issue to our support team so we can investigate and resolve the problem. [Report Issue]

### ISSUE THREAD

**Issue by krzysiekknap** [Shardeum/shardeum-bug-reporting#816]
I have not been able to run the node for few days. Is this due to work on Shardeum:Atomium?

**Comment by rohitsenindia** [comment]
same issue face after install node

**Comment by anhtudo97** [comment]
Any way to bypass this issue

**Comment by Cybertr0n313** [comment]
im also having this issue. been running a node for months

**Comment by basiof** [comment]
Same here!

**Comment by basiof** [comment]
![image](https://github.com/shardeum/bug-reporting/assets/161516294/295a592b-ac5c-44d1-b302-221f77df830b)

**Comment by sskanthy** [comment]
Same for me.

**Comment by MMatias1972** [comment]
Hello, I got same problem, but I guess it is RPC connections, if you try check Chainlist it's off

**Comment by selver-sku** [comment]
Same for me...

**Comment by metawomen** [comment]
I'm also facing same issue. Not been able to access dashboard.

**Comment by canhcanh** [comment]
same for me

**Comment by kaimano** [comment]
Same here, for many days now

**Comment by stewfarq** [comment]
Same for me.  The error seems to have appeared within the last week or so.  I have the latest version of the node.  operator-cli status returns...

/home/node/app/cli/build/src/utils/fetch-network-data.js:132
        throw new Error('Unable to fetch list of nodes in the network');
              ^

Error: Unable to fetch list of nodes in the network
    at getNewActiveNode (/home/node/app/cli/build/src/utils/fetch-network-data.js:132:15)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:538:9)
    at process.processTimers (node:internal/timers:512:7)
    at async fetchDataFromNetwork (/home/node/app/cli/build/src/utils/fetch-network-data.js:67:9)
    at async fetchStakeParameters (/home/node/app/cli/build/src/utils/fetch-network-data.js:299:25)
    at async Promise.all (index 0)
    at async /home/node/app/cli/build/src/node-commands.js:222:153

**Comment by kaimano** [comment]
yes, same for me

**Comment by toppo1986** [comment]
> ![image](https://private-user-images.githubusercontent.com/161516294/344641853-295a592b-ac5c-44d1-b302-221f77df830b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MTgxMjcsIm5iZiI6MTcxOTkxNzgyNywicGF0aCI6Ii8xNjE1MTYyOTQvMzQ0NjQxODUzLTI5NWE1OTJiLWFjNWMtNDRkMS1iMzAyLTIyMWY3N2RmODMwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMlQxMDU3MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNTA5ZGI0ODk4OWI4OTc3NGNkZmVmYjA3NjNhZjhiNTIxNWU0YTdiZjAxNjNjNTExYWE5YTc1Y2QxN2QwNjNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.doyYD94iiB75wNVea5wD1IbIaxbvISU1uIr5USFlm_Y)

same is mine

**Comment by fl0wm0ti0n** [comment]
Same, also after reinstalling everything

**Comment by batyrshinas** [comment]
Same problem after try upgrade and change network to Shardeum Atomium

**Comment by dxhod** [comment]
Have the same issue

**Comment by innowile** [comment]
![shardeum](https://github.com/shardeum/bug-reporting/assets/140487676/26ecc6f8-b279-49ef-96b1-a0c2ea27e192)
I'm facing this, is it generally or just me

**Comment by Psykepro** [comment]
same here
