### ISSUE TITLE
Unable to fetch list of nodes in the network

### ISSUE THREAD

**Issue by BrunoMarshall** [Shardeum/shardeum-bug-reporting#818]
##### What is the issue?

Unable to fetch list of nodes in the network

#### What impact does the issue have?

Significant

##### How to reproduce the issue? 

1- update a validator : 
curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh

2- operator-cli gui start

3- operator-cli network-stats
......
.....
Error: Unable to fetch list of nodes in the network
    at getNewActiveNode (/home/node/app/cli/build/src/utils/fetch-network-data.js:132:15)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:538:9)
    at process.processTimers (node:internal/timers:512:7)
    at async fetchDataFromNetwork (/home/node/app/cli/build/src/utils/fetch-network-data.js:67:9)
    at async fetchStakeParameters (/home/node/app/cli/build/src/utils/fetch-network-data.js:299:25)
    at async Promise.all (index 0)
    at async /home/node/app/cli/build/src/node-commands.js:222:153

Node.js v18.16.1

**Comment by stewfarq** [comment]
Exact same issue with me.
