### ISSUE TITLE
Internal JSON-RPC error

### ISSUE THREAD

**Issue by mumtazersoy** [Shardeum/shardeum-bug-reporting#891]
[allLogs.zip](https://github.com/user-attachments/files/16757299/allLogs.zip)
##### What is the issue?

:red_circle:  "Internal JSON-RPC error." when trying to remove stake. :red_circle: 
    
#### What impact does the issue have?

:red_circle: Describe if the bug is a visual warning or if it breaks functionality causing a system to fail. :red_circle: 

##### How to reproduce the issue? 

:red_circle: 
Explain in as much detail as possible to help reproduce the bug:
```
    -where the error is seen
    -how the error was potentially caused if possible (mention previous steps taken to see the error if relevant)
    -share code and explain how the code was run
```
:red_circle: 

##### What other resources can you share regarding this issue?

:red_circle: Photos and links related to the error. :red_circle:

**Comment by bagyanugraha** [comment]
I got the same problem





{
  isInternalTx: true,
  internalTXType: 7,
  nominator: '0xad4b41de93b7833abea2c10ecea2b867f56743c4',
  timestamp: 1725039760202,
  nominee: '18654305c8d1173196e40d8e35cabf9a564a822cadd8c539d49ebb7e6ac9c15d',
  force: false
}
{
  from: '0xAD4b41dE93b7833abeA2c10eceA2B867F56743c4',
  to: '0x0000000000000000000000000000000000010000',
  gasPrice: BigNumber { _hex: '0x3f84fc7516', _isBigNumber: true },
  gasLimit: 30000000,
  data: '0x7b226973496e7465726e616c5478223a747275652c22696e7465726e616c545854797065223a372c226e6f6d696e61746f72223a22307861643462343164653933623738333361626561326331306563656132623836376635363734336334222c2274696d657374616d70223a313732353033393736303230322c226e6f6d696e6565223a2231383635343330356338643131373331393665343064386533356361626639613536346138323263616464386335333964343965626237653661633963313564222c22666f726365223a66616c73657d',
  nonce: 21
}
Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":53,\"error\":{\"code\":101,\"message\":\"This node is in the network's Standby list. You can unstake only after the node leaves the Standby list!\",\"data\":{}}}", error={"code":101,"data":{}}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0xf9013f15853f84fc75168401c9c38094000000000000000000000000000000000001000080b8d67b226973496e7465726e616c5478223a747275652c22696e7465726e616c545854797065223a372c226e6f6d696e61746f72223a22307861643462343164653933623738333361626561326331306563656132623836376635363734336334222c2274696d657374616d70223a313732353033393736303230322c226e6f6d696e6565223a2231383635343330356338643131373331393665343064386533356361626639613536346138323263616464386335333964343965626237653661633963313564222c22666f726365223a66616c73657d823f48a0d258d289539ff87bc22e3292be548c435e7aa6dcb46522ff6fc783280c91acf1a017d37b0b20bb36a904bc10c8f2df18daf5a5d864afee80c6f352059e0064c9e5\"],\"id\":53,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://atomium.shardeum.org", code=SERVER_ERROR, version=web/5.7.1)
    at Logger.makeError (/home/node/app/cli/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/home/node/app/cli/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at /home/node/app/cli/node_modules/@ethersproject/web/lib/index.js:313:32
    at step (/home/node/app/cli/node_modules/@ethersproject/web/lib/index.js:33:23)
    at Object.next (/home/node/app/cli/node_modules/@ethersproject/web/lib/index.js:14:53)
    at fulfilled (/home/node/app/cli/node_modules/@ethersproject/web/lib/index.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  reason: 'processing response error',
  code: 'SERVER_ERROR',
  body: `{"jsonrpc":"2.0","id":53,"error":{"code":101,"message":"This node is in the network's Standby list. You can unstake only after the node leaves the Standby list!","data":{}}}`,
  error: Error: This node is in the network's Standby list. You can unstake only after the node leaves the Standby list!
      at getResult (/home/node/app/cli/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:191:21)
      at processJsonFunc (/home/node/app/cli/node_modules/@ethersproject/web/lib/index.js:356:22)
      at /home/node/app/cli/node_modules/@ethersproject/web/lib/index.js:288:46
      at step (/home/node/app/cli/node_modules/@ethersproject/web/lib/index.js:33:23)
      at Object.next (/home/node/app/cli/node_modules/@ethersproject/web/lib/index.js:14:53)
      at fulfilled (/home/node/app/cli/node_modules/@ethersproject/web/lib/index.js:5:58)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    code: 101,
    data: {}
  },
  requestBody: '{"method":"eth_sendRawTransaction","params":["0xf9013f15853f84fc75168401c9c38094000000000000000000000000000000000001000080b8d67b226973496e7465726e616c5478223a747275652c22696e7465726e616c545854797065223a372c226e6f6d696e61746f72223a22307861643462343164653933623738333361626561326331306563656132623836376635363734336334222c2274696d657374616d70223a313732353033393736303230322c226e6f6d696e6565223a2231383635343330356338643131373331393665343064386533356361626639613536346138323263616464386335333964343965626237653661633963313564222c22666f726365223a66616c73657d823f48a0d258d289539ff87bc22e3292be548c435e7aa6dcb46522ff6fc783280c91acf1a017d37b0b20bb36a904bc10c8f2df18daf5a5d864afee80c6f352059e0064c9e5"],"id":53,"jsonrpc":"2.0"}',
  requestMethod: 'POST',
  url: 'https://atomium.shardeum.org',
  transaction: {
    nonce: 21,
    gasPrice: BigNumber { _hex: '0x3f84fc7516', _isBigNumber: true },
    gasLimit: BigNumber { _hex: '0x01c9c380', _isBigNumber: true },
    to: '0x0000000000000000000000000000000000010000',
    value: BigNumber { _hex: '0x00', _isBigNumber: true },
    data: '0x7b226973496e7465726e616c5478223a747275652c22696e7465726e616c545854797065223a372c226e6f6d696e61746f72223a22307861643462343164653933623738333361626561326331306563656132623836376635363734336334222c2274696d657374616d70223a313732353033393736303230322c226e6f6d696e6565223a2231383635343330356338643131373331393665343064386533356361626639613536346138323263616464386335333964343965626237653661633963313564222c22666f726365223a66616c73657d',
    chainId: 8082,
    v: 16200,
    r: '0xd258d289539ff87bc22e3292be548c435e7aa6dcb46522ff6fc783280c91acf1',
    s: '0x17d37b0b20bb36a904bc10c8f2df18daf5a5d864afee80c6f352059e0064c9e5',
    from: '0xAD4b41dE93b7833abeA2c10eceA2B867F56743c4',
    hash: '0xb11c2611f162a18eaaa7ca5d4f7c7f1f7638c507b40ff31e510b328b86d14e19',
    type: null,
    confirmations: 0
  },
  transactionHash: '0xb11c2611f162a18eaaa7ca5d4f7c7f1f7638c507b40ff31e510b328b86d14e19'
}
