### ISSUE TITLE
Login to dashboard doesn't work

### ISSUE THREAD

**Issue by KamilValtech** [Shardeum/shardeum-bug-reporting#909]
I can't login to the dashboard at all. After login it redirects me back to login page.

I've checked browser developer tools and there is and 400 Bad request error on /auth/login endpoint. The response is:

{
  "errorMessage": "Unable to check login",
  "errorDetails": "Command failed: operator-cli gui login 7aed5af1d9e603df9d65cc434e13e4658d363e9b46535c68d532b21978569387\n/home/node/app/cli/build/src/gui-commands.js:165\n        if (!(0, crypto_1.timingSafeEqual)(Buffer.from(password), Buffer.from(config.gui.pass))) {\n                                          ^\n\nRangeError: Input buffers must have the same byte length\n    at Command.<anonymous> (/home/node/app/cli/build/src/gui-commands.js:165:43)\n    at Command.listener [as _actionHandler] (/home/node/app/cli/node_modules/commander/lib/command.js:482:17)\n    at /home/node/app/cli/node_modules/commander/lib/command.js:1283:65\n    at Command._chainOrCall (/home/node/app/cli/node_modules/commander/lib/command.js:1177:12)\n    at Command._parseCommand (/home/node/app/cli/node_modules/commander/lib/command.js:1283:27)\n    at /home/node/app/cli/node_modules/commander/lib/command.js:1081:27\n    at Command._chainOrCall (/home/node/app/cli/node_modules/commander/lib/command.js:1177:12)\n    at Command._dispatchSubcommand (/home/node/app/cli/node_modules/commander/lib/command.js:1077:23)\n    at Command._parseCommand (/home/node/app/cli/node_modules/commander/lib/command.js:1248:19)\n    at /home/node/app/cli/node_modules/commander/lib/command.js:1081:27 {\n  code: 'ERR_CRYPTO_TIMING_SAFE_EQUAL_LENGTH'\n}\n\nNode.js v18.16.1\n"
}

**Comment by Krikor-tech** [comment]
@KamilValtech Thanks for posting the issue. 

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://cryptorectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**
