### ISSUE TITLE
Error: Unable to fetch data from network (out of retries: status 404).

### ISSUE THREAD

**Issue by huma80** [Shardeum/shardeum-bug-reporting#938]
##### What is the issue?
Тode does not start:

node@ceffdc33ba73:~/app$ operator-cli status
/home/node/app/cli/build/src/utils/fetch-network-data.js:109
        throw new Error(`Unable to fetch data from network (out of retries: ${reason}).`);
              ^

Error: Unable to fetch data from network (out of retries: status 404).
    at fetchDataFromNetwork (/home/node/app/cli/build/src/utils/fetch-network-data.js:109:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchUnstakeableDetails (/home/node/app/cli/build/src/utils/fetch-network-data.js:246:24)
    at async /home/node/app/cli/build/src/node-commands.js:246:44

Node.js v18.16.1

![shardeumerror](https://github.com/user-attachments/assets/ea220135-0cdf-4710-b580-bd13e97a2650)

**Comment by cryptostoertje** [comment]
Same here.
I have managed to 'force unstake' after update and can't start in Gui. In CLI I have give the start command for the node but after checken status I get the same error.

**Comment by P4sc4lS** [comment]
same error here too

**Comment by imv007** [comment]
Here is how i fixed it by making a clean install. Now Node is starting but can't stake or force unstake my previous stake as node is on the standby list. Any idea how to fix this?

Run following commands in terminal one by one.
1. docker ps  (copy your container id)
2. docker stop container id
3. docker rm container id

4. rm -rf .shardeum

5. curl -O https://raw.githubusercontent.com/shardeum/validator-dashboard/main/installer.sh && chmod +x installer.sh && ./installer.sh

**Comment by phy-chain** [comment]
@imv007 That's an option,although I've seen people in Discord saying that they've tried that without success.
Also, if you rm the shardeum folder, how do you preserve your secrets.json file and other important file for a restart with the same validator ?

**Comment by imv007** [comment]
> @imv007 That's an option,although I've seen people in Discord saying that they've tried that without success. Also, if you rm the shardeum folder, how do you preserve your secrets.json file and other important file for a restart with the same validator ?

Well it all depends if you manage to unstake your previous stake then all is well as you can use your previous wallet to stake again. You can store your private key via cli as mentioned in documentation and stake and unstake via cli.

**Comment by imv007** [comment]
Well finally i managed to force unstake via cli after waiting ~ 48 hours

**Comment by imv007** [comment]
update: 
After unstaking i tried to stake but got rpc error so did that via cli and noticed the nonce error so i manually updated the nonce in MM (You can see your nonce via explorer it is mentioned under your balance) 

So updating the nonce managed to stake again but after staking in dashboard node status is changed from "need stake" to "stoped" and upon checking via cli now i am getting the same error: "Unable to fetch data from network (out of retries: status 404)" So i've made full circle ... in short this doesn't work... wait for update
