### ISSUE TITLE
Validator CLI `operator-cli unstake` and `operator-cli stake 10` error `could not detect network`

### ISSUE THREAD

**Issue by madf12** [Shardeum/shardeum-bug-reporting#97]
##### What is the issue?

Cannot stake or unstake with Validator CLI.
    
#### What impact does the issue have?

Makes it difficult to stake or unstake outside the Validator GUI. 

##### How to reproduce the issue? 

Staking:

PRIV_KEY is set inside the Validator CLI:

```shell
export PRIV_KEY=<WALLET_PRIVATE_KEY>
```

Verify private key is set inside the Validator CLI:

```shell
echo $PRIV_KEY
```

With the wallet set inside the Validator CLI, you can now run:

Stake:

```shell
operator-cli stake 10
```

Unstake:

```shell
operator-cli unstake
```

Both return:

```shell
Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)
    at Logger.makeError (/home/node/app/cli/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/home/node/app/cli/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at JsonRpcProvider.<anonymous> (/home/node/app/cli/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:609:54)
    at step (/home/node/app/cli/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/home/node/app/cli/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/home/node/app/cli/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'could not detect network',
  code: 'NETWORK_ERROR',
  event: 'noNetwork'
}
```

**Comment by MarcusWentz** [comment]
From what it looks like, the Validator is looking at the wrong network. 

We have a fix for this coming soon. 

Bug patch fix:

https://gitlab.com/shardeum/validator/cli/-/commit/166165ef9aa0de681941c13fc923c8e164207ddd

**Comment by NigYoA** [comment]
Hi all. Any update reagrding this issue? I  have simillar situtation. Unstake gives same error: 

Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)
    at Logger.makeError (/home/node/app/cli/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/home/node/app/cli/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at JsonRpcProvider.<anonymous> (/home/node/app/cli/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:609:54)
    at step (/home/node/app/cli/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/home/node/app/cli/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/home/node/app/cli/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'could not detect network',
  code: 'NETWORK_ERROR',
  event: 'noNetwork'

**Comment by DShafrane** [comment]
Same problem. Issue still persist

> Hi all. Any update reagrding this issue? I have simillar situtation. Unstake gives same error:
> 
> Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2) at Logger.makeError (/home/node/app/cli/node_modules/@ethersproject/logger/lib/index.js:238:21) at Logger.throwError (/home/node/app/cli/node_modules/@ethersproject/logger/lib/index.js:247:20) at JsonRpcProvider. (/home/node/app/cli/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:609:54) at step (/home/node/app/cli/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23) at Object.throw (/home/node/app/cli/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53) at rejected (/home/node/app/cli/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65) at processTicksAndRejections (node:internal/process/task_queues:96:5) { reason: 'could not detect network', code: 'NETWORK_ERROR', event: 'noNetwork'

**Comment by MarcusWentz** [comment]
Working now after uninstalling:

https://docs.shardeum.org/node/run/validator#uninstall-validator

then reinstalling:

https://docs.shardeum.org/node/run/validator#step-2-download-and-install-validator
